/**
 * 🛠️ Authoritative Nexus Tool Configuration Registry
 * Maps each toolId to its real name, type, description, and capabilities.
 * Single source of truth for the entire toolkit ecosystem.
 */

// Tool template types
export const TOOL_TYPES = {
  SCANNER: 'scanner',         // Input + Live scan results
  ANALYZER: 'analyzer',       // Input + Analysis report
  UTILITY: 'utility',         // Interactive client-side/passive tool
};

// Tool status levels
export const TOOL_STATUS = {
  LIVE: 'live',               // Real scanning, fully functional
  PARTIAL: 'partial',         // Works but requires credentials
  COMING_SOON: 'coming_soon', // Diagnostic / Passive Execution Mode
};

// Input types for tools
export const INPUT_TYPES = {
  IP: 'ip',
  URL: 'url',
  DOMAIN: 'domain',
  HASH: 'hash',
  USERNAME: 'username',
  TEXT: 'text',
  EMAIL: 'email',
  NONE: 'none',
};

// Official Nexus categories
export const CATEGORIES = {
  RECON: 'Reconnaissance',
  DNS_NET: 'DNS & Network Intelligence',
  WEB: 'Web Security',
  VULN: 'Vulnerability Assessment',
  INTEL: 'Threat Intelligence',
  OSINT: 'OSINT',
  CLOUD: 'Cloud Security',
  API: 'API Security',
  AUTH_IDENTITY: 'Authentication & Identity Security',
  MOBILE: 'Mobile Security',
  CONTAINER: 'Container & Kubernetes Security',
  DEVSECOPS: 'DevSecOps / Supply Chain Security',
  MALWARE: 'Malware Analysis',
  FORENSICS: 'Digital Forensics',
  REVERSE: 'Binary / Reverse Engineering',
  WIRELESS: 'Wireless Security',
  EMAIL: 'Email Security',
  SOCIAL_PHISHING: 'Social Engineering / Phishing Defense',
  AI: 'AI / LLM Security',
  PRIVACY: 'Privacy & Data Security',
  INCIDENT: 'Incident Response',
  MONITORING: 'Security Monitoring',
  COMPLIANCE: 'Compliance / Security Posture',
  UTILITIES: 'Utilities / Encoding / Cryptography'
};

export const CATEGORY_METADATA = {
  [CATEGORIES.RECON]: {
    purpose: 'Network and domain discovery.',
    description: 'Discover hosts, scan open ports, gather domain ownership details, and inspect network pathways.'
  },
  [CATEGORIES.DNS_NET]: {
    purpose: 'DNS diagnostics and network analysis.',
    description: 'Resolve DNS records, check name servers, and inspect IP routing details.'
  },
  [CATEGORIES.WEB]: {
    purpose: 'Web application and HTTPS security audits.',
    description: 'Inspect SSL certificates, analyze security response headers, and scan websites for misconfigurations.'
  },
  [CATEGORIES.VULN]: {
    purpose: 'Vulnerability and CVE detection.',
    description: 'Identify known security vulnerabilities (CVEs) and check software versions.'
  },
  [CATEGORIES.INTEL]: {
    purpose: 'Threat reputation and data breach monitoring.',
    description: 'Scan IP/domain blacklists, query malware reputation feeds, and check breach records.'
  },
  [CATEGORIES.OSINT]: {
    purpose: 'Open-source intelligence gathering.',
    description: 'Search public web records, usernames, and domain metadata sources.'
  },
  [CATEGORIES.CLOUD]: {
    purpose: 'Cloud security and storage auditing.',
    description: 'Inspect permissions on public cloud buckets and check cloud infrastructure configurations.'
  },
  [CATEGORIES.API]: {
    purpose: 'API endpoint security testing.',
    description: 'Test API routes and query parameters to find security flaws.'
  },
  [CATEGORIES.AUTH_IDENTITY]: {
    purpose: 'Authentication and token security.',
    description: 'Verify JWT tokens, check password security policies, and test auth protocols.'
  },
  [CATEGORIES.MOBILE]: {
    purpose: 'Mobile app security analysis.',
    description: 'Inspect Android (APK) and iOS applications for hardcoded secrets and security flaws.'
  },
  [CATEGORIES.CONTAINER]: {
    purpose: 'Docker and Kubernetes security.',
    description: 'Audit Dockerfile configurations, container images, and Kubernetes cluster settings.'
  },
  [CATEGORIES.DEVSECOPS]: {
    purpose: 'Source code and supply chain security.',
    description: 'Scan package dependencies, lockfiles, and git repositories for leaked secrets and known CVEs.'
  },
  [CATEGORIES.MALWARE]: {
    purpose: 'File and malware analysis.',
    description: 'Analyze executable strings, file hashes, and inspect suspicious files.'
  },
  [CATEGORIES.FORENSICS]: {
    purpose: 'Digital forensics and log inspection.',
    description: 'Analyze system event logs, memory dumps, and examine digital evidence.'
  },
  [CATEGORIES.REVERSE]: {
    purpose: 'Binary inspection and disassembly.',
    description: 'Inspect executable file headers, strings, and assembly instructions.'
  },
  [CATEGORIES.WIRELESS]: {
    purpose: 'Wi-Fi and wireless network security.',
    description: 'Evaluate Wi-Fi encryption strength, SSID beacons, and channel configurations.'
  },
  [CATEGORIES.EMAIL]: {
    purpose: 'Email security and anti-spoofing checks.',
    description: 'Verify SPF, DKIM, and DMARC DNS records to prevent email impersonation.'
  },
  [CATEGORIES.SOCIAL_PHISHING]: {
    purpose: 'Phishing detection and defense.',
    description: 'Detect phishing links, suspicious domain typos, and inspect scam messages.'
  },
  [CATEGORIES.AI]: {
    purpose: 'AI and prompt security.',
    description: 'Check AI inputs for prompt injections, jailbreaks, and sanitize inputs.'
  },
  [CATEGORIES.PRIVACY]: {
    purpose: 'Data privacy and tracking protection.',
    description: 'Verify cookie security attributes and inspect data encryption settings.'
  },
  [CATEGORIES.INCIDENT]: {
    purpose: 'Incident response checklists.',
    description: 'Follow step-by-step security response workflows and remediation checklists.'
  },
  [CATEGORIES.MONITORING]: {
    purpose: 'Security logs and monitoring.',
    description: 'Inspect server logs, track access patterns, and detect anomalous activity.'
  },
  [CATEGORIES.COMPLIANCE]: {
    purpose: 'Compliance and posture checks.',
    description: 'Check security configurations against standard frameworks like SOC 2, ISO 27001, and NIST.'
  },
  [CATEGORIES.UTILITIES]: {
    purpose: 'Encoding and cryptography tools.',
    description: 'Encode/decode Base64, parse JWTs, generate hashes, and calculate subnet masks.'
  }
};

const TOOL_CONFIG = {
  // ─── RECONNAISSANCE ────────────────────────────────────────────────────────
  dns: {
    id: 'dns',
    name: 'DNS Enumeration Engine',
    tagline: 'Query primary DNS records for infrastructure mapping',
    description: 'Lookup primary DNS records (A, MX, NS) and discover subdomains to map remote hosting architecture.',
    category: CATEGORIES.RECON,
    type: TOOL_TYPES.SCANNER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.DOMAIN,
    inputPlaceholder: 'Enter domain name (e.g., example.com)',
    apiEndpoint: '/toolkit/execute',
    icon: '🌐',
    color: '#0ea5e9',
    capabilities: ['A/MX/NS lookup', 'Subdomain discovery', 'Zone enumeration'],
  },
  whois: {
    id: 'whois',
    name: 'WHOIS Record Engine',
    tagline: 'Query public records for domain ownership data',
    description: 'Look up registration details, registrar, creation date, and name servers.',
    category: CATEGORIES.RECON,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.DOMAIN,
    inputPlaceholder: 'Enter domain name',
    apiEndpoint: '/tools/whois',
    icon: '🌐',
    color: '#06b6d4',
    capabilities: ['Registrar info', 'Expiry dates', 'Name servers'],
  },
  port: {
    id: 'port',
    name: 'Port Scanner',
    tagline: 'Discover open ports and network services',
    description: 'Scan open ports and discover network services running on target hosts.',
    category: CATEGORIES.RECON,
    type: TOOL_TYPES.SCANNER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.IP,
    inputPlaceholder: 'Enter target IP address or hostname',
    apiEndpoint: '/toolkit/execute',
    icon: '🔌',
    color: '#3b82f6',
    capabilities: ['TCP port check', 'Common service scan', 'Banner grabbing'],
  },
  service_fingerprint: {
    id: 'service_fingerprint',
    name: 'Service Fingerprinting',
    tagline: 'Audit version banners for running services',
    description: 'Connects to remote ports to grab network banners and match signature software versions.',
    category: CATEGORIES.RECON,
    type: TOOL_TYPES.SCANNER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.IP,
    inputPlaceholder: 'Enter target IP or hostname',
    apiEndpoint: '/toolkit/execute',
    icon: '🔍',
    color: '#8b5cf6',
    capabilities: ['Banner matching', 'Protocol validation', 'Service identification'],
  },
  subfinder: {
    id: 'subfinder',
    name: 'Subdomain Discovery Engine',
    tagline: 'Discover subdomains via Certificate Transparency and DNS probes',
    description: 'Discovers active and passive subdomains using global Certificate Transparency logs and live DNS resolution.',
    category: CATEGORIES.RECON,
    type: TOOL_TYPES.SCANNER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.DOMAIN,
    inputPlaceholder: 'Enter target domain (e.g. example.com)',
    apiEndpoint: '/toolkit/execute',
    icon: '🛰️',
    color: '#6366f1',
    capabilities: ['Certificate Transparency (crt.sh)', 'Live IP resolution', 'Wildcard deduplication'],
  },
  masscan: {
    id: 'masscan',
    name: 'Masscan Parallel Port Prober',
    tagline: 'High-speed asynchronous network port and CIDR range prober',
    description: 'High-speed asynchronous port scanner designed to scan host lists and CIDR subnets in seconds with banner extraction.',
    category: CATEGORIES.RECON,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.IP,
    inputPlaceholder: 'Enter target IP or CIDR range (e.g. 192.168.1.0/24)',
    apiEndpoint: '/toolkit/execute',
    icon: '🚀',
    color: '#f43f5e',
    capabilities: ['Asynchronous probing (10k pkts/s)', 'CIDR range mapping', 'Service banner extraction'],
  },
  'shodan-query': {
    id: 'shodan-query',
    name: 'Shodan Node & Intelligence Search',
    tagline: 'Lookup server profiles, open ports, and CVEs in Shodan intelligence feeds',
    description: 'Queries Shodan databases for open ports, vulnerabilities, and geographic metadata associated with an IP address.',
    category: CATEGORIES.RECON,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.IP,
    inputPlaceholder: 'Enter IP address or domain target (e.g. 93.184.216.34)',
    apiEndpoint: '/toolkit/execute',
    icon: '🪐',
    color: '#f59e0b',
    capabilities: ['Open ports & banners lookup', 'Known CVE vulnerability index', 'ASN & geolocation metadata'],
  },
  'censys-search': {
    id: 'censys-search',
    name: 'Censys Host & Certificate Explorer',
    tagline: 'Inspect public TLS certificate configurations and cipher suites in Censys indices',
    description: 'Inspect public certificate configurations, Subject Alternative Names (SANs), and open services records in Censys search registries.',
    category: CATEGORIES.RECON,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.IP,
    inputPlaceholder: 'Enter target domain or IP address (e.g. example.com)',
    apiEndpoint: '/toolkit/execute',
    icon: '🔮',
    color: '#ec4899',
    capabilities: ['TLS certificate search', 'Cipher suites & ALPN audit', 'Certificate Transparency logs'],
  },

  // ─── DNS & NETWORK INTELLIGENCE ───────────────────────────────────────────
  dnsx: {
    id: 'dnsx',
    name: 'Dnsx Multi-Record Resolver',
    tagline: 'High-speed DNS multi-record and CNAME resolver',
    description: 'Resolves all DNS records (A, AAAA, MX, TXT, NS, CNAME, SOA, CAA) in parallel with latency metrics.',
    category: CATEGORIES.DNS_NET,
    type: TOOL_TYPES.SCANNER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.DOMAIN,
    inputPlaceholder: 'Enter domain name (e.g. google.com)',
    apiEndpoint: '/toolkit/execute',
    icon: '🧬',
    color: '#06b6d4',
    capabilities: ['Parallel multi-record resolution', 'DNS latency benchmarking', 'SOA & CAA policy inspection'],
  },
  traceroute: {
    id: 'traceroute',
    name: 'Traceroute Visualizer',
    tagline: 'Trace network hops, transit latency, and packet routing to destination',
    description: 'Traces the intermediate gateway and backbone hops network packets pass through to reach target hosts.',
    category: CATEGORIES.DNS_NET,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.IP,
    inputPlaceholder: 'Enter host or IP address (e.g. 1.1.1.1 or example.com)',
    apiEndpoint: '/toolkit/execute',
    icon: '🗺️',
    color: '#10b981',
    capabilities: ['ICMP path route trace', 'Hop latency mapping', 'AS transit discovery'],
  },
  'bgp-route-audit': {
    id: 'bgp-route-audit',
    name: 'BGP Routing & RPKI Validator',
    tagline: 'Audit autonomous system announcements and RPKI ROA cryptographic validity',
    description: 'Inspects global BGP routing configurations, announced prefixes, and RPKI ROA signature status to detect path hijacking risks.',
    category: CATEGORIES.DNS_NET,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.IP,
    inputPlaceholder: 'Enter target IP or ASN (e.g. 1.1.1.1 or AS13335)',
    apiEndpoint: '/toolkit/execute',
    icon: '🔀',
    color: '#f97316',
    capabilities: ['Origin ASN lookup', 'RPKI ROA validation status', 'Tier-1 transit peers mapping'],
  },
  'dnssec-audit': {
    id: 'dnssec-audit',
    name: 'DNSSEC Key Validator',
    tagline: 'Audit domain cryptographic record validation',
    description: 'Verifies the cryptographic signatures (RRSIG, DNSKEY, DS) of domain records to detect DNS spoofing risks.',
    category: CATEGORIES.DNS_NET,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.DOMAIN,
    inputPlaceholder: 'Enter domain name (e.g. cloudflare.com)',
    apiEndpoint: '/toolkit/execute',
    icon: '🔑',
    color: '#8b5cf6',
    capabilities: ['DNSKEY verification', 'DS records check', 'Signature validity check'],
  },
  'ipv6-checker': {
    id: 'ipv6-checker',
    name: 'IPv6 Address Validator',
    tagline: 'Audit IPv6 network infrastructure mapping',
    description: 'Performs configuration checks to confirm target availability over IPv6 networks and dual-stack architecture.',
    category: CATEGORIES.DNS_NET,
    type: TOOL_TYPES.SCANNER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.DOMAIN,
    inputPlaceholder: 'Enter target domain or hostname',
    apiEndpoint: '/toolkit/execute',
    icon: '💾',
    color: '#14b8a6',
    capabilities: ['AAAA record lookup', 'IPv6 routing test', 'Dual-stack compatibility audit'],
  },
  'mac-lookup': {
    id: 'mac-lookup',
    name: 'MAC OUI Parser',
    tagline: 'Query hardware address vendor registries',
    description: 'Resolves the Manufacturer and Organization Unique Identifier (OUI) registration metadata of a MAC address.',
    category: CATEGORIES.DNS_NET,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter MAC address (e.g. 00:1A:2B:3C:4D:5E)',
    apiEndpoint: '/toolkit/execute',
    icon: '💻',
    color: '#6b7280',
    capabilities: ['OUI lookup', 'Format normalization', 'Vendor metadata retrieval'],
  },

  // ─── WEB SECURITY ─────────────────────────────────────────────────────────
  tech_detection: {
    id: 'tech_detection',
    name: 'Technology Detection',
    tagline: 'Identify frameworks and versions from web request responses',
    description: 'Analyze web headers and page source code to identify technology stacks, frameworks, and versions.',
    category: CATEGORIES.WEB,
    type: TOOL_TYPES.SCANNER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.URL,
    inputPlaceholder: 'Enter website URL (e.g., https://example.com)',
    apiEndpoint: '/toolkit/execute',
    icon: '⚙️',
    color: '#3b82f6',
    capabilities: ['Web stack discovery', 'CMS identification', 'Server version grab'],
  },
  http: {
    id: 'http',
    name: 'HTTP Header Auditor',
    tagline: 'Inspect HTTP responses security header attributes',
    description: 'Analyze HTTP security headers configuration policies (CSP, HSTS, CORS, XFO).',
    category: CATEGORIES.WEB,
    type: TOOL_TYPES.SCANNER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.URL,
    inputPlaceholder: 'Enter target URL',
    apiEndpoint: '/toolkit/execute',
    icon: '🌍',
    color: '#10b981',
    capabilities: ['CSP policy check', 'HSTS validation', 'XFO audit'],
  },
  ssl: {
    id: 'ssl',
    name: 'SSL/TLS Certificate Audit',
    tagline: 'Inspect TLS certificate properties and chains',
    description: 'Look up active TLS certificate details, including expiration, issuer, signature key sizes, and cipher suites.',
    category: CATEGORIES.WEB,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.DOMAIN,
    inputPlaceholder: 'Enter domain name',
    apiEndpoint: '/tools/ssl',
    icon: '🔒',
    color: '#f59e0b',
    capabilities: ['Certificate validity', 'Cipher suites audit', 'Trust chain check'],
  },
  whatweb: {
    id: 'whatweb',
    name: 'WhatWeb Technology Scanner',
    tagline: 'Next-generation web technology identification and software stack fingerprinter',
    description: 'Identifies content management systems (CMS), web servers, JavaScript frameworks, analytics, and security headers.',
    category: CATEGORIES.WEB,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.URL,
    inputPlaceholder: 'Enter website URL (e.g. https://example.com)',
    apiEndpoint: '/toolkit/execute',
    icon: '🕸️',
    color: '#f43f5e',
    capabilities: ['CMS & framework detection', 'Web server & CDN identification', 'Analytics & JS library audit'],
  },
  dirsearch: {
    id: 'dirsearch',
    name: 'Dirsearch Path Prober',
    tagline: 'Probe web servers for exposed config files and sensitive administrative paths',
    description: 'Probes high-value sensitive endpoints (/.env, /.git, /admin, /swagger.json, /robots.txt) to identify unintended exposure.',
    category: CATEGORIES.WEB,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.URL,
    inputPlaceholder: 'Enter target website URL (e.g. https://example.com)',
    apiEndpoint: '/toolkit/execute',
    icon: '📁',
    color: '#a855f7',
    capabilities: ['Sensitive file (.env, .git) probe', 'Admin portal discovery', 'HTTP status code mapping'],
  },
  wpscan: {
    id: 'wpscan',
    name: 'WPScan WordPress Auditor',
    tagline: 'Audit WordPress core version, user enumeration, and XML-RPC exposure',
    description: 'Black box WordPress scanner assessing core version exposure, XML-RPC active endpoints, and REST API user enumeration.',
    category: CATEGORIES.WEB,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.URL,
    inputPlaceholder: 'Enter WordPress website URL (e.g. https://wordpress-site.com)',
    apiEndpoint: '/toolkit/execute',
    icon: '📝',
    color: '#2563eb',
    capabilities: ['Core version detection', 'REST API author user enumeration', 'XML-RPC endpoint audit'],
  },
  'cors-scanner': {
    id: 'cors-scanner',
    name: 'CORS Configuration Auditor',
    tagline: 'Audit Cross-Origin Resource Sharing rules and origin reflection',
    description: 'Sends custom origin probes to detect arbitrary origin reflection, wildcard exposures, and insecure credentials trust.',
    category: CATEGORIES.WEB,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.URL,
    inputPlaceholder: 'Enter website URL (e.g. https://example.com)',
    apiEndpoint: '/toolkit/execute',
    icon: '🔄',
    color: '#0ea5e9',
    capabilities: ['Arbitrary origin reflection probe', 'Null origin sandbox testing', 'Credentials header vulnerability audit'],
  },
  'csp-evaluator': {
    id: 'csp-evaluator',
    name: 'CSP Policy Evaluator',
    tagline: 'Inspect Content Security Policy bypasses and calculate security grade',
    description: 'Parses CSP directives and flags potential XSS injection bypasses, missing fallbacks, and insecure sources.',
    category: CATEGORIES.WEB,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter website URL or paste CSP header value',
    apiEndpoint: '/toolkit/execute',
    icon: '📊',
    color: '#10b981',
    capabilities: ['Security grade calculation (A+ to F)', 'XSS script-src bypass detection', 'Object-src & Frame-ancestors audit'],
  },

  // ─── VULNERABILITY ASSESSMENT ─────────────────────────────────────────────
  'cve-lookup': {
    id: 'cve-lookup',
    name: 'CVE Vulnerability Inspector',
    tagline: 'Search CVE database and inspect CVSS 3.1 severity scores',
    description: 'Queries global CVE registries to inspect vulnerability descriptions, affected products, CVSS scores, and patches.',
    category: CATEGORIES.VULN,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter CVE ID (e.g. CVE-2021-44228) or product name',
    apiEndpoint: '/toolkit/execute',
    icon: '🛡️',
    color: '#ef4444',
    capabilities: ['CVSS 3.1 score calculation', 'CWE classification', 'Vulnerable product matching'],
  },
  nikto: {
    id: 'nikto',
    name: 'Nikto Web Vulnerability Scanner',
    tagline: 'Scan web servers for dangerous files, outdated banners, and configuration flaws',
    description: 'Finds dangerous files, outdated server software, and specific configuration mistakes on target web hosts.',
    category: CATEGORIES.VULN,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.URL,
    inputPlaceholder: 'Enter target web URL (e.g. https://example.com)',
    apiEndpoint: '/toolkit/execute',
    icon: '🎯',
    color: '#ef4444',
    capabilities: ['Server banner audit', 'Missing security headers linter', 'Sensitive path & CGI probe'],
  },
  sqlmap: {
    id: 'sqlmap',
    name: 'SQLmap Injection & Database Auditor',
    tagline: 'Automated parameter SQL injection and database vulnerability audit',
    description: 'Evaluates URL query parameters and forms for Boolean-based, error-based, UNION-based, and time-based SQL injection bugs.',
    category: CATEGORIES.VULN,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.URL,
    inputPlaceholder: 'Enter target URL with parameters (e.g. https://api.example.com/items?id=10)',
    apiEndpoint: '/toolkit/execute',
    icon: '🛢️',
    color: '#f59e0b',
    capabilities: ['Boolean & Error SQLi checks', 'UNION-based queries audit', 'Backend DBMS fingerprinting'],
  },
  trivy: {
    id: 'trivy',
    name: 'Trivy Container & Lockfile Auditor',
    tagline: 'Scan container images, Dockerfiles, and lockfiles for CVE vulnerabilities',
    description: 'Audit container images, lockfiles, and directories for software package vulnerabilities (CVEs) and root misconfigurations.',
    category: CATEGORIES.VULN,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter container image tag (e.g. alpine:3.18) or paste Dockerfile/lockfile',
    apiEndpoint: '/toolkit/execute',
    icon: '📦',
    color: '#06b6d4',
    capabilities: ['OS packages CVE check', 'Critical/High severity breakdown', 'Container misconfiguration audit'],
  },
  zap: {
    id: 'zap',
    name: 'OWASP ZAP Dynamic Web Application Scanner',
    tagline: 'Dynamic Application Security Testing (DAST) for OWASP Top 10 flaws',
    description: 'Audit web applications for reflected XSS, missing anti-CSRF tokens, sensitive header leaks, and insecure cookies.',
    category: CATEGORIES.VULN,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.URL,
    inputPlaceholder: 'Enter target web application URL (e.g. https://app.example.com)',
    apiEndpoint: '/toolkit/execute',
    icon: '⚡',
    color: '#10b981',
    capabilities: ['OWASP Top 10 vulnerability checks', 'Passive DAST spidering', 'DAST Posture Score (0-100)'],
  },
  burp: {
    id: 'burp',
    name: 'Burp Suite Enterprise DAST',
    tagline: 'Automated DAST vulnerability scans and Burp Collaborator OOB testing',
    description: 'Enterprise dynamic application security testing (DAST) crawling web endpoints and identifying injection vulnerabilities and OOB interactions.',
    category: CATEGORIES.VULN,
    type: TOOL_TYPES.SCANNER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.URL,
    inputPlaceholder: 'Enter target web URL (e.g. https://app.example.com)',
    apiEndpoint: '/toolkit/execute',
    icon: '💼',
    color: '#f97316',
    capabilities: ['Burp Collaborator OOB interaction test', 'SQLi / XSS / SSRF vulnerability detection', 'Crawled endpoints & DAST posture score'],
  },
  nuclei: {
    id: 'nuclei',
    name: 'Nuclei Template-Based Vulnerability Scanner',
    tagline: 'Execute curated security templates for CVEs, misconfigurations, and exposures',
    description: 'Runs customizable templates against target endpoints to discover CVE configurations, Git exposures, and API token leaks.',
    category: CATEGORIES.VULN,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.URL,
    inputPlaceholder: 'Enter target web URL or host (e.g. https://api.example.com)',
    apiEndpoint: '/toolkit/execute',
    icon: '🎯',
    color: '#e11d48',
    capabilities: ['Template-based CVE signatures', 'Git / API schema exposure match', 'Severity classification (Critical/High)'],
  },
  openvas: {
    id: 'openvas',
    name: 'OpenVAS Network Vulnerability Engine',
    tagline: 'Comprehensive Network Vulnerability Test (NVT) suite and CVSS scoring',
    description: 'Executes comprehensive Network Vulnerability Tests (NVT) against active services, scoring vulnerabilities via CVSS v3.1.',
    category: CATEGORIES.VULN,
    type: TOOL_TYPES.SCANNER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.IP,
    inputPlaceholder: 'Enter target IP or host (e.g. 192.168.1.100 or host.corp.net)',
    apiEndpoint: '/toolkit/execute',
    icon: '⚙️',
    color: '#7c3aed',
    capabilities: ['NVT signature scan library (68k+ checks)', 'CVSS v3.1 severity rating & CVE mapping', 'Port/service vulnerability remediation index'],
  },

  // ─── THREAT INTELLIGENCE ──────────────────────────────────────────────────
  url: {
    id: 'url',
    name: 'URL Threat Intelligence',
    tagline: 'Check reputation marks and analyze malicious links',
    description: 'Scan URLs and IPs against threat intelligence databases to identify malware and abuse.',
    category: CATEGORIES.INTEL,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.URL,
    inputPlaceholder: 'Enter URL or IP',
    apiEndpoint: '/toolkit/execute',
    icon: '☣️',
    color: '#394eff',
    capabilities: ['Reputation check', 'Malware detection', 'Phishing detection'],
  },
  breach: {
    id: 'breach',
    name: 'Breach Checker',
    tagline: 'Scan for dark web email credentials compromise',
    description: 'Queries public and private repositories of compromised credentials to identify data leaks.',
    category: CATEGORIES.INTEL,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.EMAIL,
    inputPlaceholder: 'Enter email address',
    apiEndpoint: '/breach/email',
    icon: '🔑',
    color: '#e11d48',
    capabilities: ['Credential leak audit', 'SHA-1 k-Anonymity password check', 'Dark web exposure intelligence'],
  },
  'alienvault-otx': {
    id: 'alienvault-otx',
    name: 'AlienVault OTX Threat Pulse Search',
    tagline: 'Query open threat exchange indicators, pulses, and adversary tags',
    description: 'Searches the AlienVault platform database for threat activity pulses associated with an IP or Domain.',
    category: CATEGORIES.INTEL,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.DOMAIN,
    inputPlaceholder: 'Enter target domain or IP (e.g. example.com or 8.8.8.8)',
    apiEndpoint: '/toolkit/execute',
    icon: '🛸',
    color: '#10b981',
    capabilities: ['Threat pulse retrieval', 'Adversary & malware tag tracking', 'Reputation scoring'],
  },
  virusshare: {
    id: 'virusshare',
    name: 'VirusShare Malware Hash Searcher',
    tagline: 'Verify file hash integrity and classify malware sample signatures',
    description: 'Compares a file hash (MD5, SHA1, SHA256) against malware sample repositories to flag known trojans and ransomware.',
    category: CATEGORIES.INTEL,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.HASH,
    inputPlaceholder: 'Enter MD5, SHA-1, or SHA-256 file checksum',
    apiEndpoint: '/toolkit/execute',
    icon: '🦠',
    color: '#ef4444',
    capabilities: ['Hash matching & signature verification', 'Malware family classification', 'PE32 / ELF header profiling'],
  },
  'misp-lookup': {
    id: 'misp-lookup',
    name: 'MISP Threat Sharing IOC Checker',
    tagline: 'Query malware information sharing platform events and MITRE tactics',
    description: 'Searches local and remote Malware Information Sharing Platform instances for compromises, threat actors, and TTPs.',
    category: CATEGORIES.INTEL,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.DOMAIN,
    inputPlaceholder: 'Enter target domain, IP, or hash (e.g. 198.51.100.25)',
    apiEndpoint: '/toolkit/execute',
    icon: '📡',
    color: '#f97316',
    capabilities: ['MISP event correlation', 'MITRE ATT&CK technique mapping', 'Threat actor attribution'],
  },
  abuseipdb: {
    id: 'abuseipdb',
    name: 'AbuseIPDB Threat Reporter',
    tagline: 'Check IP abuse confidence score and reputation reports',
    description: 'Queries threat intelligence networks to inspect whether an IP is reported for spam, botnet, or brute-force attacks.',
    category: CATEGORIES.INTEL,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.IP,
    inputPlaceholder: 'Enter IP address (e.g. 1.1.1.1)',
    apiEndpoint: '/toolkit/execute',
    icon: '☣️',
    color: '#e11d48',
    capabilities: ['Abuse confidence score calculation', 'ISP & ASN metadata lookup', 'Malicious incident history'],
  },

  // ─── OSINT ────────────────────────────────────────────────────────────────
  harvester: {
    id: 'harvester',
    name: 'TheHarvester Intelligence Gatherer',
    tagline: 'Harvest public emails, employee names, subdomains, and hostnames',
    description: 'Active intelligence gatherer querying search engines, PGP key registries, and Shodan databases.',
    category: CATEGORIES.OSINT,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.DOMAIN,
    inputPlaceholder: 'Enter target domain (e.g. example.com)',
    apiEndpoint: '/toolkit/execute',
    icon: '🌾',
    color: '#8b5cf6',
    capabilities: ['Email enumeration', 'Subdomain & host discovery', 'Search engine & PGP parsing'],
  },
  sherlock: {
    id: 'sherlock',
    name: 'Sherlock Social Profiler',
    tagline: 'Search username profiles across major social platforms',
    description: 'Searches public account profiles across major developer and social platforms (GitHub, Reddit, Twitter/X, Telegram, Dev.to, Medium, etc.).',
    category: CATEGORIES.OSINT,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.USERNAME,
    inputPlaceholder: 'Enter username (e.g. torvalds)',
    apiEndpoint: '/toolkit/execute',
    icon: '🕵️',
    color: '#10b981',
    capabilities: ['Multi-platform profile discovery', 'Direct profile URL generation', 'Claimed account verification'],
  },
  'hunter-io': {
    id: 'hunter-io',
    name: 'Hunter Domain Email Pattern Search',
    tagline: 'Discover corporate email patterns and executive contact directory',
    description: 'Identify common email syntax patterns and exposed professional email addresses associated with a corporate domain.',
    category: CATEGORIES.OSINT,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.DOMAIN,
    inputPlaceholder: 'Enter target company domain (e.g. stripe.com)',
    apiEndpoint: '/toolkit/execute',
    icon: '🎯',
    color: '#f97316',
    capabilities: ['Email pattern schema detection', 'Executive contact extraction', 'Department distribution breakdown'],
  },
  intelx: {
    id: 'intelx',
    name: 'Intelligence X Archive Explorer',
    tagline: 'Search historical breach archives, dark web indexes, and pastebin leaks',
    description: 'Searches historic leak data archives, paste sites, and dark web indexes for target domains, emails, or search terms.',
    category: CATEGORIES.OSINT,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter domain, email, username, or search term (e.g. acme-corp.com)',
    apiEndpoint: '/toolkit/execute',
    icon: '🔮',
    color: '#6366f1',
    capabilities: ['Historical leak archives query', 'Tor darknet forum search', 'Pastebin leak matching'],
  },

  // ─── CLOUD SECURITY ───────────────────────────────────────────────────────
  prowler: {
    id: 'prowler',
    name: 'Prowler AWS CIS Benchmark Auditor',
    tagline: 'Audit AWS infrastructure against CIS Foundations Benchmark standards',
    description: 'Evaluates AWS asset configurations against CIS benchmark standards covering IAM, S3 encryption, CloudTrail, and VPC networking.',
    category: CATEGORIES.CLOUD,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter AWS Region or Account identifier (e.g. us-east-1)',
    apiEndpoint: '/toolkit/execute',
    icon: '🤠',
    color: '#ec4899',
    capabilities: ['CIS AWS Foundations Benchmark', 'IAM root MFA & wildcard policy checks', 'CloudTrail & Security Group audits'],
  },
  scoutsuite: {
    id: 'scoutsuite',
    name: 'Scout Suite Multi-Cloud Auditor',
    tagline: 'Multi-cloud resource configuration and security posture auditor',
    description: 'Audit service configurations in AWS, Azure, and GCP, flagging excessive access and missing logs.',
    category: CATEGORIES.CLOUD,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter cloud provider identifier or manifest (e.g. AWS & GCP Multi-Cloud)',
    apiEndpoint: '/toolkit/execute',
    icon: '👁️',
    color: '#3b82f6',
    capabilities: ['AWS & GCP multi-cloud review', 'Storage ACL & KMS encryption check', 'Kubernetes GKE & IAM audit'],
  },
  'bucket-finder': {
    id: 'bucket-finder',
    name: 'Cloud Storage Bucket Finder',
    tagline: 'Scan public storage bucket permissions on AWS S3 and GCP',
    description: 'Brute-forces common naming parameters to detect public bucket exposures on S3 and GCP storage.',
    category: CATEGORIES.CLOUD,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter company keyword or domain (e.g. acme-corp)',
    apiEndpoint: '/toolkit/execute',
    icon: '🛢️',
    color: '#10b981',
    capabilities: ['AWS S3 bucket mutation scan', 'GCP storage permissions check', 'Public Read/Write risk detection'],
  },
  'iam-policy-audit': {
    id: 'iam-policy-audit',
    name: 'IAM Policy Security Linter',
    tagline: 'Audit AWS IAM JSON policy documents for excessive wildcard permissions',
    description: 'Parses raw JSON IAM policies to identify full AdministratorAccess, wildcard actions, and dangerous privilege escalations.',
    category: CATEGORIES.CLOUD,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Paste AWS IAM JSON policy document here',
    apiEndpoint: '/toolkit/execute',
    icon: '📑',
    color: '#8b5cf6',
    capabilities: ['Wildcard action check', 'Administrator access audit', 'Security score calculation (0-100)'],
  },

  // ─── API SECURITY ─────────────────────────────────────────────────────────
  'postman-audit': {
    id: 'postman-audit',
    name: 'Postman Collection Auditor',
    tagline: 'Audit Postman API collections for hardcoded API keys and unencrypted routes',
    description: 'Parses exported Postman collection JSON schemas (v2.0/v2.1) to identify hardcoded Bearer tokens, plaintext HTTP endpoints, and exposed parameters.',
    category: CATEGORIES.API,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Paste exported Postman Collection JSON here',
    apiEndpoint: '/toolkit/execute',
    icon: '📮',
    color: '#f97316',
    capabilities: ['Hardcoded API keys detection', 'Plaintext HTTP URL audit', 'Security score calculation (0-100)'],
  },
  'jwt-strength': {
    id: 'jwt-strength',
    name: 'JWT Strength & Signature Auditor',
    tagline: 'Verify JWT signature algorithm, expiration timestamps, and payload PII leakage',
    description: 'Audits JWT validation policies by checking cryptographic parameters (alg: none), token expiration, and payload data privacy.',
    category: CATEGORIES.API,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Paste 3-part JWT token (header.payload.signature)',
    apiEndpoint: '/toolkit/execute',
    icon: '🔑',
    color: '#06b6d4',
    capabilities: ['Alg none vulnerability check', 'Token expiration audit', 'Payload sensitive PII detection'],
  },
  'api-fuzzer': {
    id: 'api-fuzzer',
    name: 'API Endpoint Fuzzer & Injection Tester',
    tagline: 'Fuzz endpoint parameters for boundary handling, type juggling, and server exceptions',
    description: 'Sends boundary test vectors and injection payloads to API endpoints to detect unhandled exceptions and validation overrides.',
    category: CATEGORIES.API,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.URL,
    inputPlaceholder: 'Enter API URL endpoint (e.g. https://api.example.com/v1/users?id=1)',
    apiEndpoint: '/toolkit/execute',
    icon: '🧪',
    color: '#ef4444',
    capabilities: ['Boundary & large buffer tests', 'SQLi / XSS payload filtration checks', 'Server exception & 500 error monitoring'],
  },
  'oas-linter': {
    id: 'oas-linter',
    name: 'OpenAPI / Swagger Spec Linter',
    tagline: 'Audit Swagger and OpenAPI schemas for missing security blocks and exposed routes',
    description: 'Lints OpenAPI v2/v3 YAML/JSON schemas to identify unauthenticated routes, plain HTTP servers, and missing security schemas.',
    category: CATEGORIES.API,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Paste OpenAPI / Swagger YAML or JSON schema here',
    apiEndpoint: '/toolkit/execute',
    icon: '📋',
    color: '#10b981',
    capabilities: ['Global security block audit', 'Insecure HTTP server check', 'Security score calculation (0-100)'],
  },

  // ─── AUTHENTICATION & IDENTITY SECURITY ───────────────────────────────────
  hydra: {
    id: 'hydra',
    name: 'Hydra Protocol Authentication Auditor',
    tagline: 'Audit protocol credentials strength and lockout resilience on SSH, FTP, HTTP',
    description: 'Simulates dictionary authentication attempts on SSH, FTP, or HTTP endpoints to detect default credentials and evaluate account lockout policies.',
    category: CATEGORIES.AUTH_IDENTITY,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter protocol and host (e.g. ssh://192.168.1.10 or http://app.example.com)',
    apiEndpoint: '/toolkit/execute',
    icon: '🐉',
    color: '#dc2626',
    capabilities: ['Default credential dictionary testing', 'Account lockout rate-limit audit', 'Auth strength score (0-100)'],
  },
  'ldap-audit': {
    id: 'ldap-audit',
    name: 'LDAP Policy Auditor',
    tagline: 'Audit Active Directory auth rules, cleartext transport, and anonymous search',
    description: 'Inspects LDAP security rules to identify anonymous search options, cleartext transport, and NTLM fallback policies.',
    category: CATEGORIES.AUTH_IDENTITY,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.IP,
    inputPlaceholder: 'Enter LDAP server host or IP (e.g. ldap.example.com)',
    apiEndpoint: '/toolkit/execute',
    icon: '📇',
    color: '#4f46e5',
    capabilities: ['Anonymous binding checks', 'TLS policy review', 'Attributes mapping list'],
  },
  'saml-decoder': {
    id: 'saml-decoder',
    name: 'SAML Assertion Decoder',
    tagline: 'Decode SAML XML tokens and validate signatures and expiration',
    description: 'Decodes Base64 and XML SAML tokens to inspect Issuer identity, Subject NameID, validity conditions, and cryptographic signatures.',
    category: CATEGORIES.AUTH_IDENTITY,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Paste Base64 SAML response or raw XML assertion',
    apiEndpoint: '/toolkit/execute',
    icon: '🏷️',
    color: '#0891b2',
    capabilities: ['XML signature check', 'Token expiration validation', 'Attributes & claims extraction'],
  },
  'oauth-validator': {
    id: 'oauth-validator',
    name: 'OAuth Route Validator',
    tagline: 'Test OAuth 2.0 / OIDC redirect URI and security parameters',
    description: 'Verifies authorization endpoints to detect open redirect vulnerabilities, missing CSRF state parameters, and PKCE enforcement.',
    category: CATEGORIES.AUTH_IDENTITY,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.URL,
    inputPlaceholder: 'Enter OAuth authorization URL (e.g. https://auth.example.com/authorize?...)',
    apiEndpoint: '/toolkit/execute',
    icon: '🛂',
    color: '#65a30d',
    capabilities: ['State CSRF parameter validation', 'PKCE code_challenge audit', 'Redirect URI safety check'],
  },

  // ─── MOBILE SECURITY ──────────────────────────────────────────────────────
  'mobsf-apk': {
    id: 'mobsf-apk',
    name: 'MobSF Android Manifest Analyzer',
    tagline: 'Static analysis of AndroidManifest.xml for dangerous permissions and exported components',
    description: 'Queries Android manifest configurations to identify dangerous permissions, exported un-permissioned activities, and debuggable flags.',
    category: CATEGORIES.MOBILE,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Paste AndroidManifest.xml or manifest dump here',
    apiEndpoint: '/toolkit/execute',
    icon: '📱',
    color: '#d946ef',
    capabilities: ['Dangerous permissions audit', 'Exported component check', 'Security score calculation (0-100)'],
  },
  'ipa-signer-check': {
    id: 'ipa-signer-check',
    name: 'iOS IPA & Entitlements Validator',
    tagline: 'Audit iOS Info.plist and entitlements for debugging flags and ATS bypasses',
    description: 'Inspects iOS application entitlements and Info.plist to check get-task-allow, ATS HTTP exceptions, and keychain access groups.',
    category: CATEGORIES.MOBILE,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Paste Info.plist or embedded.mobileprovision XML text here',
    apiEndpoint: '/toolkit/execute',
    icon: '🍏',
    color: '#3b82f6',
    capabilities: ['get-task-allow debugging check', 'App Transport Security (ATS) audit', 'Security score calculation (0-100)'],
  },
  'apk-leak-finder': {
    id: 'apk-leak-finder',
    name: 'APK Credentials & Secrets Extractor',
    tagline: 'Scan mobile resources and strings tables for hardcoded API keys and cloud secrets',
    description: 'Parses assets and strings tables inside mobile packages to locate hardcoded Firebase URLs, Google Maps API keys, and AWS credentials.',
    category: CATEGORIES.MOBILE,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Paste mobile app strings.xml or decompiled resources here',
    apiEndpoint: '/toolkit/execute',
    icon: '🚰',
    color: '#10b981',
    capabilities: ['Firebase & Google API key match', 'AWS & Stripe token detection', 'Cleartext staging URL extraction'],
  },
  androguard: {
    id: 'androguard',
    name: 'Androguard Dalvik Bytecode Disassembler',
    tagline: 'Reverse engineer Dalvik DEX instructions for reflection, dynamic loading, and weak ciphers',
    description: 'Inspects Dalvik DEX bytecode instructions to detect dynamic reflection, DexClassLoader calls, and insecure cryptographic ciphers (AES/ECB).',
    category: CATEGORIES.MOBILE,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Paste Dalvik bytecode, smali instructions, or method dump here',
    apiEndpoint: '/toolkit/execute',
    icon: '🛡️',
    color: '#84cc16',
    capabilities: ['Dynamic reflection detection', 'DexClassLoader code loading audit', 'Weak cipher (AES/ECB) identification'],
  },

  // ─── CONTAINER & KUBERNETES SECURITY ──────────────────────────────────────
  'kube-bench': {
    id: 'kube-bench',
    name: 'Kube-Bench CIS Benchmark Auditor',
    tagline: 'Audit Kubernetes master and worker node configurations against CIS controls',
    description: 'Checks Kubernetes daemon configurations and control plane files against recommendations in the CIS Kubernetes Benchmark standards.',
    category: CATEGORIES.CONTAINER,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter cluster context name or manifest (e.g. production-k8s-cluster)',
    apiEndpoint: '/toolkit/execute',
    icon: '☸️',
    color: '#06b6d4',
    capabilities: ['Control plane components check', 'etcd encryption review', 'Worker node & kubelet audit'],
  },
  kubesec: {
    id: 'kubesec',
    name: 'Kubesec Manifest Linter',
    tagline: 'Verify Kubernetes deployment YAML manifest security score',
    description: 'Reviews Kubernetes resource definitions to detect root privileges, missing resource bounds, and insecure capabilities.',
    category: CATEGORIES.CONTAINER,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Paste Kubernetes YAML manifest here',
    apiEndpoint: '/toolkit/execute',
    icon: '☸️',
    color: '#6366f1',
    capabilities: ['Privileged container checking', 'Capabilities whitelist audit', 'Security score calculation (0-100)'],
  },
  'docker-bench': {
    id: 'docker-bench',
    name: 'Docker CIS Benchmark Auditor',
    tagline: 'Audit Docker daemon security profiles, privileged containers, and socket exposures',
    description: 'Evaluates Docker daemon security configurations and compose templates against CIS Docker Benchmark controls (0-100 score).',
    category: CATEGORIES.CONTAINER,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Paste Docker configuration, compose YAML, or CLI flags',
    apiEndpoint: '/toolkit/execute',
    icon: '🐳',
    color: '#0ea5e9',
    capabilities: ['Privileged container check', 'Docker socket mount audit', 'CIS compliance score (0-100)'],
  },
  'falco-logs': {
    id: 'falco-logs',
    name: 'Falco Container Syscall Inspector',
    tagline: 'Audit container runtime alerts and anomalous system call execution traces',
    description: 'Audits container runtime event streams to detect interactive terminal spawns, unauthorized /etc/shadow access, and outbound C2 traffic.',
    category: CATEGORIES.CONTAINER,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Paste Falco JSON event stream or container syslog lines',
    apiEndpoint: '/toolkit/execute',
    icon: '🦅',
    color: '#10b981',
    capabilities: ['Interactive shell spawn detection', 'Sensitive file (/etc/shadow) access trace', 'C2 outbound port alert'],
  },

  // ─── DEVSECOPS / SUPPLY CHAIN SECURITY ────────────────────────────────────
  semgrep: {
    id: 'semgrep',
    name: 'Semgrep SAST Code Auditor',
    tagline: 'Static application security testing for dynamic code execution and injection vulnerabilities',
    description: 'Scans source code (JS, Python, PHP, Java, Go) for dangerous sinks like eval(), SQL string concatenation, and command injections.',
    category: CATEGORIES.DEVSECOPS,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Paste source code snippet here to analyze',
    apiEndpoint: '/toolkit/execute',
    icon: '🔍',
    color: '#f43f5e',
    capabilities: ['Dynamic code execution check', 'SQL string concatenation detector', 'CWE vulnerability mapping'],
  },
  gitleaks: {
    id: 'gitleaks',
    name: 'Gitleaks Secrets Scanner',
    tagline: 'Scan text and code for leaked API keys and cloud credentials',
    description: 'Scans source code, config files, and commit logs against 20+ patterns of cloud keys, tokens, and private secrets.',
    category: CATEGORIES.DEVSECOPS,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Paste source code or configuration text here',
    apiEndpoint: '/toolkit/execute',
    icon: '🩸',
    color: '#dc2626',
    capabilities: ['AWS & Google Cloud key detection', 'GitHub PAT & Stripe secret match', 'Private RSA/SSH key identification'],
  },
  'dependency-track': {
    id: 'dependency-track',
    name: 'Dependency-Track SBOM Auditor',
    tagline: 'Scan package.json, requirements.txt, or SBOM files for known CVE packages',
    description: 'Compares Software Bill of Materials (SBOM) data against database indexes of known CVE packages and security advisories.',
    category: CATEGORIES.DEVSECOPS,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Paste package.json, requirements.txt, or CycloneDX SBOM JSON',
    apiEndpoint: '/toolkit/execute',
    icon: '📊',
    color: '#8b5cf6',
    capabilities: ['SBOM component parsing', 'Known CVE package matching', 'Remediation patch advisory'],
  },
  'snyk-test': {
    id: 'snyk-test',
    name: 'Snyk Dependency & CVE Checker',
    tagline: 'Scan package dependencies for known code CVEs and patch advisories',
    description: 'Identifies known CVE alerts and vulnerable dependency chains in third-party libraries, providing direct remediation paths.',
    category: CATEGORIES.DEVSECOPS,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Paste package.json, pom.xml, or dependencies manifest',
    apiEndpoint: '/toolkit/execute',
    icon: '🐶',
    color: '#4f46e5',
    capabilities: ['Dependency vulnerability scan', 'Severity breakdown (Critical/High)', 'Direct upgrade remediation path'],
  },

  // ─── MALWARE ANALYSIS ─────────────────────────────────────────────────────
  'yara-rules': {
    id: 'yara-rules',
    name: 'YARA Signature Matcher',
    tagline: 'Classify malware signatures, webshells, C2 beacons, and ransomware notes',
    description: 'Evaluates file contents and script strings against built-in YARA signature rules to identify webshells, miners, and backdoors.',
    category: CATEGORIES.MALWARE,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Paste suspicious file strings, script, or hex payload here',
    apiEndpoint: '/toolkit/execute',
    icon: '📜',
    color: '#ea580c',
    capabilities: ['Webshell & backdoor detection', 'Cobalt Strike C2 beacon match', 'Ransomware note classification'],
  },
  peframe: {
    id: 'peframe',
    name: 'PE Binary Header & Packer Analyzer',
    tagline: 'Static analysis of Windows PE/EXE headers, UPX packers, and dangerous API imports',
    description: 'Inspects Windows Portable Executable (PE) headers to extract packer signatures (UPX), section entropy, and process injection APIs.',
    category: CATEGORIES.MALWARE,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Paste PE header dump, section dump, or imports table',
    apiEndpoint: '/toolkit/execute',
    icon: '🧱',
    color: '#0d9488',
    capabilities: ['UPX packer detection', 'Section entropy calculation', 'Suspicious Win32 API audit'],
  },
  'cuckoo-sandbox': {
    id: 'cuckoo-sandbox',
    name: 'Cuckoo Dynamic Malware Sandbox Detonator',
    tagline: 'Simulate dynamic binary execution, process trees, and C2 beacons in isolated VM',
    description: 'Simulates behavioral detonation of executable/document samples in isolated sandboxes, analyzing dynamic process trees, modified registry keys, and network DNS/C2 queries.',
    category: CATEGORIES.MALWARE,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter sample filename or paste execution dump (e.g. invoice_march.exe)',
    apiEndpoint: '/toolkit/execute',
    icon: '🐦',
    color: '#0ea5e9',
    capabilities: ['Dynamic process tree detonation', 'Registry run key persistence audit', 'MITRE ATT&CK tactics mapping'],
  },
  pdfid: {
    id: 'pdfid',
    name: 'PDF Security & Malware Inspector',
    tagline: 'Scan PDF files and raw streams for embedded scripts and launch triggers',
    description: 'Scans PDF structures looking for malicious /JavaScript blocks, automatic /OpenAction triggers, and /Launch execution commands.',
    category: CATEGORIES.MALWARE,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Paste raw PDF header or stream content here',
    apiEndpoint: '/toolkit/execute',
    icon: '📄',
    color: '#f43f5e',
    capabilities: ['Embedded JavaScript detection', 'Auto launch trigger audit', 'Threat score calculation (0-100)'],
  },

  // ─── DIGITAL FORENSICS ────────────────────────────────────────────────────
  autopsy: {
    id: 'autopsy',
    name: 'Autopsy Digital Forensics & File Carving',
    tagline: 'Inspect disk images for carved files, USB insertion traces, and event timelines',
    description: 'Analyzes forensic disk images and raw file dumps, extracting file carving metadata, deleted items, and chronological incident timeline records.',
    category: CATEGORIES.FORENSICS,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter disk image path or forensic partition identifier (e.g. /dev/sdb1)',
    apiEndpoint: '/toolkit/execute',
    icon: '🕵️',
    color: '#6b7280',
    capabilities: ['Deleted & orphan file carving', 'Chronological event timeline reconstruction', 'Evidence SHA-256 integrity validation'],
  },
  volatility: {
    id: 'volatility',
    name: 'Volatility Memory Analysis',
    tagline: 'Extract running processes, injected VAD regions, and network sockets from RAM dumps',
    description: 'Inspects volatile memory dumps to find active process trees, injected DLL modules (malfind), and listening TCP/UDP sockets.',
    category: CATEGORIES.FORENSICS,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter absolute path to RAM dump file (e.g. memory.dmp or raw image)',
    apiEndpoint: '/toolkit/execute',
    icon: '🧠',
    color: '#8b5cf6',
    capabilities: ['Active process tree extraction', 'Injected VAD memory regions (malfind)', 'Network socket & TCP/UDP connection audit'],
  },
  sleuthkit: {
    id: 'sleuthkit',
    name: 'The Sleuth Kit (TSK)',
    tagline: 'Partition layouts, NTFS MFT parsing, and unallocated inode carving',
    description: 'Parses partition schemes (GPT/MBR) and raw disk sectors to discover deleted Master File Table (MFT) records and orphan filesystem entries.',
    category: CATEGORIES.FORENSICS,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter path to raw volume file or partition (e.g. /dev/sda2)',
    apiEndpoint: '/toolkit/execute',
    icon: '🛠️',
    color: '#10b981',
    capabilities: ['GPT / MBR partition layout parsing', 'NTFS Master File Table ($MFT) analysis', 'Deleted & unallocated sector cluster search'],
  },
  plaso: {
    id: 'plaso',
    name: 'Plaso Super-Timeline Engine',
    tagline: 'Aggregate multi-source event logs into a unified forensic timeline',
    description: 'Aggregates metadata and event logs from multiple files (winevtx, prefetch, MFT, chrome history) to compile unified chronological timeline records.',
    category: CATEGORIES.FORENSICS,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter directory path containing logs or forensic dump',
    apiEndpoint: '/toolkit/execute',
    icon: '⏳',
    color: '#f59e0b',
    capabilities: ['Multi-parser log aggregation', 'Super-timeline chronological matrix', 'Staging, execution & lateral movement tagging'],
  },

  // ─── BINARY / REVERSE ENGINEERING ─────────────────────────────────────────
  ghidra: {
    id: 'ghidra',
    name: 'Ghidra Headless Decompiler',
    tagline: 'Decompile binary files, analyze instruction sets, and identify dangerous API sinks',
    description: 'Decompiles binary files into C pseudo-code, analyzing function call graphs, compiler signatures, and dangerous API primitives (VirtualAllocEx).',
    category: CATEGORIES.REVERSE,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter binary path or paste function snippet (e.g. agent_implant.bin)',
    apiEndpoint: '/toolkit/execute',
    icon: '🐲',
    color: '#10b981',
    capabilities: ['Headless decompilation & C pseudo-code', 'Process injection primitive identification', 'Suspicious Win32/POSIX API import audit'],
  },
  radare2: {
    id: 'radare2',
    name: 'Radare2 Analysis & Shellcode Inspector',
    tagline: 'Disassemble opcodes, analyze shellcode, and inspect hexadecimal instructions',
    description: 'Command line tool for binary decompilation, shellcode execution, and hex analysis.',
    category: CATEGORIES.REVERSE,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter binary path or raw hex bytes (e.g. 31 c0 50 68...)',
    apiEndpoint: '/toolkit/execute',
    icon: '💻',
    color: '#3b82f6',
    capabilities: ['x86 / x64 opcode disassembly', 'Syscall identification & comment annotations', 'Null-byte free shellcode validation'],
  },
  binwalk: {
    id: 'binwalk',
    name: 'Binwalk Firmware Analyzer',
    tagline: 'Analyze firmware images for embedded SquashFS, U-Boot, and kernel magic headers',
    description: 'Finds embedded filesystems, bootloader headers, and compression blocks inside binary firmware images with entropy scoring.',
    category: CATEGORIES.REVERSE,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Paste firmware binary header, hex dump, or partition text here',
    apiEndpoint: '/toolkit/execute',
    icon: '📦',
    color: '#d97706',
    capabilities: ['Embedded filesystem detection', 'Entropy calculation (0-8)', 'Magic header signature mapping'],
  },
  capstone: {
    id: 'capstone',
    name: 'Capstone Opcode Disassembler',
    tagline: 'Disassemble raw hex machine opcodes into x86/x64 and ARM assembly instructions',
    description: 'Multi-architecture disassembly engine converting hex byte streams into mnemonics, operands, and register operations.',
    category: CATEGORIES.REVERSE,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter raw hex opcodes (e.g. 55 48 89 e5 48 83 ec 10)',
    apiEndpoint: '/toolkit/execute',
    icon: '⚙️',
    color: '#4b5563',
    capabilities: ['x86/x64 opcode decode', 'Mnemonic & operand breakdown', 'Syscall transition identification'],
  },

  // ─── WIRELESS SECURITY ────────────────────────────────────────────────────
  'aircrack-ng': {
    id: 'aircrack-ng',
    name: 'Aircrack-ng Interface',
    tagline: 'Audit captured WPA2/WPA3 4-way handshakes and password entropy',
    description: 'Inspects captured network handshakes to evaluate EAPOL MIC integrity and simulated password dictionary resilience.',
    category: CATEGORIES.WIRELESS,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter filepath to local CAP file (e.g. wpa2_corp_handshake.cap)',
    apiEndpoint: '/toolkit/execute',
    icon: '📶',
    color: '#06b6d4',
    capabilities: ['4-Way EAPOL Handshake verification', 'Cryptographic MIC validation', 'Password dictionary entropy audit'],
  },
  kismet: {
    id: 'kismet',
    name: 'Kismet Wireless Survey Parser',
    tagline: 'Inspect captured wireless survey telemetry and BSSID topology',
    description: 'Parses wireless survey files to map location topology, frequency bands (2.4/5GHz), encryption standards, and client rosters.',
    category: CATEGORIES.WIRELESS,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter path to local kismet survey log (e.g. kismet_survey.kismet)',
    apiEndpoint: '/toolkit/execute',
    icon: '📡',
    color: '#10b981',
    capabilities: ['Dual-band Access Point enumeration', 'Signal strength & RSSI parsing', 'Unencrypted open network warning'],
  },
  wifite: {
    id: 'wifite',
    name: 'Wifite Wireless Security Auditor',
    tagline: 'Automated WPS, PMKID, and Management Frame Protection (MFP) audit',
    description: 'Evaluates wireless network configurations against WPS PIN vulnerabilities, PMKID key exposure, and 802.11w Management Frame Protection compliance.',
    category: CATEGORIES.WIRELESS,
    type: TOOL_TYPES.SCANNER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter wireless interface identifier (e.g. wlan0mon or Corp-SSID)',
    apiEndpoint: '/toolkit/execute',
    icon: '🛰️',
    color: '#ef4444',
    capabilities: ['WPS PIN vulnerability check', 'Zero-client PMKID frame capture audit', '802.11w Management Frame Protection verification'],
  },
  'bt-scanner': {
    id: 'bt-scanner',
    name: 'Bluetooth Low Energy (BLE) Scanner',
    tagline: 'Discover nearby BLE peripherals, GATT services, and proximity signals',
    description: 'Queries Bluetooth controller boundaries to list BLE beacons, advertising packets, RSSI proximity, and exposed GATT service UUIDs.',
    category: CATEGORIES.WIRELESS,
    type: TOOL_TYPES.SCANNER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter controller interface (e.g. hci0 or 10s scan)',
    apiEndpoint: '/toolkit/execute',
    icon: '🌐',
    color: '#3b82f6',
    capabilities: ['BLE peripheral discovery', 'RSSI proximity distance tracking', 'Exposed GATT service UUID audit'],
  },

  // ─── EMAIL SECURITY ───────────────────────────────────────────────────────
  'mail-spoof-checker': {
    id: 'mail-spoof-checker',
    name: 'Email Spoofing & DMARC Auditor',
    tagline: 'Audit domain SPF, DKIM, and DMARC policy rules and spoof resilience',
    description: 'Inspects domain DNS TXT records to confirm mail server protection settings, SPF mechanisms, and DMARC policy enforcement.',
    category: CATEGORIES.EMAIL,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.DOMAIN,
    inputPlaceholder: 'Enter domain target (e.g. example.com) or paste TXT record',
    apiEndpoint: '/toolkit/execute',
    icon: '📧',
    color: '#f97316',
    capabilities: ['SPF records parser', 'DMARC alignment check', 'Email spoofing defense score (0-100)'],
  },
  'mxtoolbox-check': {
    id: 'mxtoolbox-check',
    name: 'MX Blacklist & RBL Auditor',
    tagline: 'Audit mail server IP reputations status and DNSBL blacklists',
    description: 'Queries IP blacklist repositories (Spamhaus, Barracuda, SpamCop) to confirm email server deliverability and reputation status.',
    category: CATEGORIES.EMAIL,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.IP,
    inputPlaceholder: 'Enter MX host domain or IP address',
    apiEndpoint: '/toolkit/execute',
    icon: '📊',
    color: '#8b5cf6',
    capabilities: ['Spamhaus list lookup', 'MX records resolution', 'Blacklist reputation query'],
  },
  phishmeister: {
    id: 'phishmeister',
    name: 'Email Header & Hop Route Analyzer',
    tagline: 'Trace mail delivery hop sequences and SPF/DKIM authentication results',
    description: 'Parses raw RFC 822 / MIME EML headers to detect hop tracing route discrepancies, client originating IP, and authentication results.',
    category: CATEGORIES.EMAIL,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Paste raw RFC 822 / MIME EML header here',
    apiEndpoint: '/toolkit/execute',
    icon: '🕵️',
    color: '#10b981',
    capabilities: ['EML hop parsing', 'Originating client IP extraction', 'SPF & DKIM auth results check'],
  },

  // ─── SOCIAL ENGINEERING / PHISHING DEFENSE ───────────────────────────────
  phishing: {
    id: 'phishing',
    name: 'Phishing Detector',
    tagline: 'Heuristically check domain names for phishing indicators',
    description: 'Performs lexical audits on input URLs to spot suspect lookalike structures and phishing markers.',
    category: CATEGORIES.SOCIAL_PHISHING,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.URL,
    inputPlaceholder: 'Enter link under analysis',
    apiEndpoint: '/tools/phishing',
    icon: '🎣',
    color: '#f43f5e',
    capabilities: ['Brand validation checks', 'Lexical domain audits', 'Character override checking'],
  },
  gophish: {
    id: 'gophish',
    name: 'GoPhish Phishing Simulation Tracker',
    tagline: 'Enterprise awareness campaign analytics, open rates, and compromise tracking',
    description: 'Tracks employee simulated phishing campaigns, reporting email delivery, open rates, click-throughs, and credential compromise statistics.',
    category: CATEGORIES.SOCIAL_PHISHING,
    type: TOOL_TYPES.SCANNER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter campaign name or template ID (e.g. Q3_Corporate_Phish_Sim)',
    apiEndpoint: '/toolkit/execute',
    icon: '🎣',
    color: '#a855f7',
    capabilities: ['Campaign delivery & open rate analytics', 'Click-through & credential compromise tracking', 'Security awareness risk classification'],
  },
  'domain-twist': {
    id: 'domain-twist',
    name: 'Domain Typosquatting & Permutation Searcher',
    tagline: 'Generate and resolve lookalike typosquatting and bit-squatting domains',
    description: 'Generates potential typosquatting, homoglyph, omission, and bit-squatting permutations of a domain and queries active registration & MX records.',
    category: CATEGORIES.SOCIAL_PHISHING,
    type: TOOL_TYPES.SCANNER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.DOMAIN,
    inputPlaceholder: 'Enter domain target (e.g. google.com or brand.com)',
    apiEndpoint: '/toolkit/execute',
    icon: '🌀',
    color: '#e11d48',
    capabilities: ['Homoglyph & bit-squatting permutations', 'Live DNS A & MX resolution check', 'Phishing lookalike threat level score'],
  },
  'evilginx-audit': {
    id: 'evilginx-audit',
    name: 'Evilginx Reverse-Proxy MFA Bypass Auditor',
    tagline: 'Audit authentication flows against reverse-proxy phishing and session theft',
    description: 'Evaluates login endpoints against reverse-proxy MITM phishing (Evilginx phishlets), analyzing session cookie flags and FIDO2/WebAuthn resilience.',
    category: CATEGORIES.SOCIAL_PHISHING,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.URL,
    inputPlaceholder: 'Enter login portal URL (e.g. https://auth.example.com/login)',
    apiEndpoint: '/toolkit/execute',
    icon: '🦊',
    color: '#ea580c',
    capabilities: ['Reverse-proxy MITM vulnerability audit', 'FIDO2 / WebAuthn origin-binding check', 'Session cookie security posture evaluation'],
  },

  // ─── AI / LLM SECURITY ────────────────────────────────────────────────────
  'prompt-guard': {
    id: 'prompt-guard',
    name: 'Prompt Injection & Jailbreak Guard',
    tagline: 'Scan LLM prompts for adversarial jailbreaks, DAN personas, and system overrides',
    description: 'Evaluates user prompts against adversarial prompt injection signatures, DAN overrides, and special token delimiters with 0–100 safety scoring.',
    category: CATEGORIES.AI,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter or paste user prompt / query to analyze',
    apiEndpoint: '/toolkit/execute',
    icon: '🛡️',
    color: '#a855f7',
    capabilities: ['System instruction override check', 'DAN jailbreak persona match', 'Prompt safety score (0-100)'],
  },
  garak: {
    id: 'garak',
    name: 'Garak LLM Vulnerability Scanner',
    tagline: 'Scan generative AI models for prompt injection, leakage, and hallucination defects',
    description: 'Executes automated security probe sweeps against target generative models to map alignment boundaries and prompt injection defenses.',
    category: CATEGORIES.AI,
    type: TOOL_TYPES.SCANNER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter model endpoint or identifier (e.g. gpt-4o, claude-3.5-sonnet, llama-3)',
    apiEndpoint: '/toolkit/execute',
    icon: '🤖',
    color: '#06b6d4',
    capabilities: ['Prompt injection & jailbreak sweeps', 'System prompt leakage validation', 'Hallucination & toxicity metrics'],
  },
  'llm-redteam': {
    id: 'llm-redteam',
    name: 'AI Red-Teaming & Alignment CLI',
    tagline: 'Adversarial jailbreak attacks, persona drift, and safety refusal testing',
    description: 'Runs adversarial attack sequences (GCG, Crescendo, Roleplay) against target LLMs to evaluate refusal boundaries and alignment resilience.',
    category: CATEGORIES.AI,
    type: TOOL_TYPES.SCANNER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter model configuration or system persona under test',
    apiEndpoint: '/toolkit/execute',
    icon: '🎯',
    color: '#dc2626',
    capabilities: ['Universal adversarial suffix tests (GCG)', 'Multi-turn persona drift evaluation', 'Refusal rate & alignment score'],
  },
  'prompt-fuzzer': {
    id: 'prompt-fuzzer',
    name: 'LLM System Prompt Boundary Fuzzer',
    tagline: 'Fuzz system prompt boundaries for delimiter escapes and instruction overrides',
    description: 'Injects special tokens, homoglyphs, and delimiter escapes into prompts to verify system prompt confidentiality and boundary integrity.',
    category: CATEGORIES.AI,
    type: TOOL_TYPES.SCANNER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter system prompt to fuzz and test for boundary leakage',
    apiEndpoint: '/toolkit/execute',
    icon: '🧪',
    color: '#10b981',
    capabilities: ['Special token & delimiter escape fuzzing', 'System prompt leak resilience scoring', 'Role confusion override testing'],
  },

  // ─── PRIVACY & DATA SECURITY ──────────────────────────────────────────────
  'gdpr-cookie-audit': {
    id: 'gdpr-cookie-audit',
    name: 'GDPR Cookie & Consent Auditor',
    tagline: 'Audit website cookies for SameSite, Secure, HttpOnly, and third-party trackers',
    description: 'Scans target website response headers to inspect tracking cookies, SameSite policies, and compliance with GDPR consent mandates.',
    category: CATEGORIES.PRIVACY,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.URL,
    inputPlaceholder: 'Enter website URL to audit (e.g. example.com)',
    apiEndpoint: '/toolkit/execute',
    icon: '🍪',
    color: '#8b5cf6',
    capabilities: ['Secure & HttpOnly flag validation', 'Third-party analytics tracker map', 'GDPR compliance score (0-100)'],
  },
  'exif-stripper': {
    id: 'exif-stripper',
    name: 'Image EXIF & Geolocation Inspector',
    tagline: 'Inspect image metadata for GPS coordinates, camera model, and privacy leaks',
    description: 'Parses image metadata headers to identify exposed GPS latitude/longitude coordinates, device serials, and timestamp leaks.',
    category: CATEGORIES.PRIVACY,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Paste EXIF metadata text, camera headers, or properties dump here',
    apiEndpoint: '/toolkit/execute',
    icon: '📷',
    color: '#14b8a6',
    capabilities: ['GPS coordinates extraction', 'Camera make & model detection', 'Privacy risk scoring'],
  },
  'pii-scanner': {
    id: 'pii-scanner',
    name: 'Sensitive PII & Compliance Scanner',
    tagline: 'Scan text payloads for Credit Cards (Luhn), SSNs, PAN, Aadhaar, and email leaks',
    description: 'Searches text payloads for personal data variables like credit cards, US SSNs, Indian PAN/Aadhaar, and email addresses with masking.',
    category: CATEGORIES.PRIVACY,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Paste text content or document dump to scan for PII',
    apiEndpoint: '/toolkit/execute',
    icon: '🔒',
    color: '#e11d48',
    capabilities: ['Credit Card Luhn verification', 'SSN / PAN / Aadhaar pattern match', 'Automated data masking'],
  },

  // ─── INCIDENT RESPONSE ────────────────────────────────────────────────────
  remediation: {
    id: 'remediation',
    name: 'AI Remediation Planner',
    tagline: 'Dynamic remediation playbook blueprints for CVE risks',
    description: 'Leverages Gemini and local signatures catalogs to generate verified remediation advice plans.',
    category: CATEGORIES.INCIDENT,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter vulnerability CVE ID (e.g. CVE-2021-34473)',
    apiEndpoint: '/toolkit/execute',
    icon: '🩹',
    color: '#a855f7',
    capabilities: ['Vulnerability mitigation steps', 'Validation rules checklists', 'System configs patches'],
  },
  thehive: {
    id: 'thehive',
    name: 'TheHive Incident Case Manager',
    tagline: 'Format security incidents, IOCs, and CVEs into standardized SIEM/SOC response cases',
    description: 'Parses security incident alerts, IOC hashes, and IPs into structured TheHive v4/v5 JSON response cases with standard playbook tasks.',
    category: CATEGORIES.INCIDENT,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter incident title, description, or paste IOCs (IPs, hashes, CVEs)',
    apiEndpoint: '/toolkit/execute',
    icon: '🐝',
    color: '#eab308',
    capabilities: ['Automated IOC extraction', 'MITRE ATT&CK case tagging', 'Playbook task list formatting'],
  },
  'misp-feed': {
    id: 'misp-feed',
    name: 'MISP Threat Feed Publisher',
    tagline: 'Package and publish IOC events, TLP tags, and threat actor galaxies',
    description: 'Packages indicators of compromise (IOCs) into standardized MISP Feed events with TLP classifications and galaxy tags for community sync.',
    category: CATEGORIES.INCIDENT,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter IOC event title, threat cluster, or paste indicators',
    apiEndpoint: '/toolkit/execute',
    icon: '📣',
    color: '#ea580c',
    capabilities: ['MISP Event JSON packaging', 'TLP classification (AMBER/GREEN/RED)', 'Threat actor galaxy tagging'],
  },
  'playbook-runner': {
    id: 'playbook-runner',
    name: 'SOC Playbook Orchestrator',
    tagline: 'Automated containment, credential revocation, and host isolation workflows',
    description: 'Executes automated security orchestration and response (SOAR) playbooks across containment, memory triage, and perimeter blocking.',
    category: CATEGORIES.INCIDENT,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter incident response playbook name (e.g. Ransomware_Endpoint_Containment_Playbook)',
    apiEndpoint: '/toolkit/execute',
    icon: '⚙️',
    color: '#06b6d4',
    capabilities: ['Automated host isolation workflow', 'Active Kerberos & OAuth token revocation', 'Perimeter firewall block execution'],
  },

  // ─── SECURITY MONITORING ──────────────────────────────────────────────────
  'wazuh-agent-audit': {
    id: 'wazuh-agent-audit',
    name: 'Wazuh SIEM Agent Auditor',
    tagline: 'Audit host Wazuh telemetry agent, FIM syscheck, and rootcheck configurations',
    description: 'Inspects host Wazuh agent telemetry streams, File Integrity Monitoring (Syscheck), and vulnerability detection modules with health scoring.',
    category: CATEGORIES.MONITORING,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter target host agent ID or paste agent ossec.conf text',
    apiEndpoint: '/toolkit/execute',
    icon: '🕵️',
    color: '#0284c7',
    capabilities: ['Syscheck FIM validation', 'Rootcheck trojan detection', 'Agent health score (0-100)'],
  },
  'zeek-logs': {
    id: 'zeek-logs',
    name: 'Zeek Network Transaction Parser',
    tagline: 'Analyze Zeek conn.log, dns.log, and http.log for network anomalies',
    description: 'Reviews network transaction files generated by Zeek/Bro sensors to detect port scans, DNS tunneling, and anomalous outbound sessions.',
    category: CATEGORIES.MONITORING,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Paste Zeek conn.log, dns.log, or http.log TSV contents here',
    apiEndpoint: '/toolkit/execute',
    icon: '👁️',
    color: '#10b981',
    capabilities: ['TSV log stream parser', 'Connection state mapping (S0/SF)', 'Suspicious session flagging'],
  },
  'auditd-viewer': {
    id: 'auditd-viewer',
    name: 'Linux Auditd Syscall Tracer',
    tagline: 'Parse Linux auditd syscall records for unauthorized privilege elevations',
    description: 'Decodes syscall records (type=SYSCALL, type=EXECVE) generated by auditd to identify root transitions and sensitive binary execution.',
    category: CATEGORIES.MONITORING,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Paste raw Linux auditd system event logs here',
    apiEndpoint: '/toolkit/execute',
    icon: '📜',
    color: '#4b5563',
    capabilities: ['Syscall event decoding', 'Privilege elevation audit (auid vs euid)', 'Process path tracing'],
  },

  // ─── COMPLIANCE / SECURITY POSTURE ────────────────────────────────────────
  'cis-cat': {
    id: 'cis-cat',
    name: 'CIS-CAT Host Baseline Benchmark Auditor',
    tagline: 'Audit Linux and Windows server configurations against CIS Level 1/2 benchmarks',
    description: 'Evaluates operating system and server configuration benchmarks against Center for Internet Security (CIS) Level 1 and Level 2 baselines.',
    category: CATEGORIES.COMPLIANCE,
    type: TOOL_TYPES.SCANNER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter target host identifier or OS profile (e.g. Ubuntu Linux 22.04 LTS)',
    apiEndpoint: '/toolkit/execute',
    icon: '📊',
    color: '#eab308',
    capabilities: ['CIS Level 1 / Level 2 benchmark rules', 'Section compliance scoring (1.0-5.0)', 'System hardening defect remediation'],
  },
  'soc2-checklist': {
    id: 'soc2-checklist',
    name: 'SOC 2 Trust Services Posture Evaluator',
    tagline: 'Assess security controls against the 5 SOC 2 Trust Services Categories',
    description: 'Validates organizational security posture against Security, Availability, Processing Integrity, Confidentiality, and Privacy criteria.',
    category: CATEGORIES.COMPLIANCE,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter environment parameters or scope (e.g. AWS Multi-Region Production)',
    apiEndpoint: '/toolkit/execute',
    icon: '📋',
    color: '#0d9488',
    capabilities: ['5 Trust Services Categories audit', 'Readiness score index (0-100)', 'Missing control gap analysis'],
  },
  'hipaa-auditor': {
    id: 'hipaa-auditor',
    name: 'HIPAA ePHI Security Rule Auditor',
    tagline: 'Audit cloud infrastructure against HIPAA Technical & Administrative Safeguards',
    description: 'Scans cloud infrastructure settings to verify ePHI encryption at rest (AES-256), TLS in transit, audit logging, and access controls.',
    category: CATEGORIES.COMPLIANCE,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter cloud infrastructure scope or configuration dump',
    apiEndpoint: '/toolkit/execute',
    icon: '🩺',
    color: '#d946ef',
    capabilities: ['§ 164.312 Technical Safeguards check', 'ePHI encryption verification', 'HIPAA compliance readiness index'],
  },

  // ─── UTILITIES / ENCODING / CRYPTOGRAPHY ──────────────────────────────────
  'jwt-parser': {
    id: 'jwt-parser',
    name: 'JWT Security Decoder',
    tagline: 'Inspect JSON Web Tokens',
    description: 'Decode and inspect JWT tokens.',
    category: CATEGORIES.UTILITIES,
    type: TOOL_TYPES.UTILITY,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Paste your JWT token here',
    apiEndpoint: null,
    icon: '🔑',
    color: '#f59e0b',
    capabilities: ['Header decode', 'Payload inspection'],
  },
  'base64-decoder': {
    id: 'base64-decoder',
    name: 'Base64 Converter',
    tagline: 'Encode and decode Base64 strings',
    description: 'Instantly convert text to/from Base64.',
    category: CATEGORIES.UTILITIES,
    type: TOOL_TYPES.UTILITY,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter text',
    apiEndpoint: null,
    icon: '🔄',
    color: '#8b5cf6',
    capabilities: ['Base64 encode', 'Base64 decode'],
  },
  'url-sanitizer': {
    id: 'url-sanitizer',
    name: 'URL Sanitizer',
    tagline: 'Parse and sanitize URLs',
    description: 'Parse URLs, extract query parameters, and identify payloads.',
    category: CATEGORIES.UTILITIES,
    type: TOOL_TYPES.UTILITY,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.URL,
    inputPlaceholder: 'Paste a URL',
    apiEndpoint: null,
    icon: '🔗',
    color: '#06b6d4',
    capabilities: ['URL parsing', 'Query extraction'],
  },
  sms: {
    id: 'sms',
    name: 'SMS Analyzer',
    tagline: 'Heuristic text analyzer for mobile smishing',
    description: 'Inspect messages for phishing indicators, financial scams, and credential harvesting patterns.',
    category: CATEGORIES.UTILITIES,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter SMS text here',
    apiEndpoint: '/tools/sms',
    icon: '📱',
    color: '#10b981',
    capabilities: ['Smishing pattern audit', 'Urgency heuristics checking', 'Shortener URL parsing'],
  },
  upi: {
    id: 'upi',
    name: 'UPI Verifier',
    tagline: 'UPI VPA validator for financial fraud checks',
    description: 'Verifies UPI virtual payment address structures and patterns for fraud verification.',
    category: CATEGORIES.UTILITIES,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter UPI ID (e.g. user@ybl)',
    apiEndpoint: '/tools/upi',
    icon: '💸',
    color: '#14b8a6',
    capabilities: ['VPA format validation', 'Handle lookup check', 'Fraud risk indexing'],
  },
  'hash-generator': {
    id: 'hash-generator',
    name: 'Cryptographic Hash Generator',
    tagline: 'Generate MD5, SHA-1, SHA-256, SHA-512, and RIPEMD-160 digests',
    description: 'Converts plaintext data into multi-algorithm cryptographic hash signatures with Shannon entropy calculations.',
    category: CATEGORIES.UTILITIES,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Enter plaintext payload or string to hash',
    apiEndpoint: '/toolkit/execute',
    icon: '🔢',
    color: '#6b7280',
    capabilities: ['SHA-256 & SHA-512 calculation', 'MD5 & SHA-1 checksums', 'Entropy bit-density calculation'],
  },
  'hex-editor': {
    id: 'hex-editor',
    name: 'Dossier Hex & Binary Frame Inspector',
    tagline: 'Inspect text and binary byte payloads in aligned 16-byte hex matrices',
    description: 'Formats strings, binary payloads, and byte dumps into hexadecimal offset grids with ASCII character sidebars.',
    category: CATEGORIES.UTILITIES,
    type: TOOL_TYPES.ANALYZER,
    status: TOOL_STATUS.LIVE,
    inputType: INPUT_TYPES.TEXT,
    inputPlaceholder: 'Paste text payload, binary bytes, or hex string here',
    apiEndpoint: '/toolkit/execute',
    icon: '💾',
    color: '#475569',
    capabilities: ['16-byte aligned offset matrices', 'ASCII character decoding sidebar', 'Byte stream length counter'],
  }
};

/**
 * Get tool configuration by ID
 * @param {string} toolId
 * @returns {object|null}
 */
export const getToolConfig = (toolId) => TOOL_CONFIG[toolId] || null;

/**
 * Get all tools as array
 * @returns {Array}
 */
export const getAllTools = () => Object.values(TOOL_CONFIG);

/**
 * Get tools by status
 * @param {string} status - TOOL_STATUS value
 * @returns {Array}
 */
export const getToolsByStatus = (status) =>
  Object.values(TOOL_CONFIG).filter((t) => t.status === status);

/**
 * Get tools by category
 * @param {string} category
 * @returns {Array}
 */
export const getToolsByCategory = (category) =>
  Object.values(TOOL_CONFIG).filter((t) => t.category === category);

/**
 * Get tools by type
 * @param {string} type - TOOL_TYPES value
 * @returns {Array}
 */
export const getToolsByType = (type) =>
  Object.values(TOOL_CONFIG).filter((t) => t.type === type);

/**
 * Get all unique categories
 * @returns {Array<string>}
 */
export const getAllCategories = () =>
  Object.values(CATEGORIES);

/**
 * Check if a tool is functional (all registered models are active)
 * @param {string} toolId
 * @returns {boolean}
 */
export const isToolActive = (toolId) => {
  const tool = TOOL_CONFIG[toolId];
  return !!tool;
};

/**
 * Get status badge info
 * @param {string} status
 * @returns {object}
 */
export const getStatusBadge = (status) => {
  switch (status) {
    case TOOL_STATUS.LIVE:
      return { label: 'LIVE ENGINE', color: '#00ff88', bg: 'rgba(0,255,136,0.1)' };
    case TOOL_STATUS.PARTIAL:
      return { label: 'DIAGNOSTIC', color: '#00bfff', bg: 'rgba(0,191,255,0.1)' };
    case TOOL_STATUS.COMING_SOON:
      return { label: 'DIAGNOSTIC', color: '#00bfff', bg: 'rgba(0,191,255,0.1)' };
    default:
      return { label: 'ACTIVE', color: '#00ff88', bg: 'rgba(0,255,136,0.1)' };
  }
};

export default TOOL_CONFIG;

