'use strict';

const csiComposition = require('../../../../server/composition/csiComposition');

describe('PipelineRegression', () => {
    it('should produce byte-identical ExecutionResultDTOs over 100 iterations', async () => {
        // Use the actual service
        const service = csiComposition.csiOrchestrationService;
        
        let baseline = null;

        for (let i = 0; i < 100; i++) {
            const result = await service.execute('example.com');

            // Deep clone so we don't mutate the frozen object directly
            const resultObj = JSON.parse(JSON.stringify(result));

            // Strip variable fields
            delete resultObj.executionId;
            delete resultObj.startedAt;
            delete resultObj.finishedAt;
            delete resultObj.durationMs;

            // Deep strip executionId/timestamps from nested objects
            // 1. Findings
            resultObj.findings.forEach(f => {
                delete f.executionId;
                delete f.timestamp; // If any
            });

            // 2. Risk
            delete resultObj.risk.executionId;
            delete resultObj.risk.timestamp;

            // 3. Correlation
            delete resultObj.correlation.executionId;
            delete resultObj.correlation.timestamp;

            // 4. Reasoning
            delete resultObj.reasoning.executionId;
            delete resultObj.reasoning.timestamp;

            // 5. Exports
            // Exports contain stringified JSON/STIX with deeply embedded executionIds and timestamps.
            // Since they are strings, parsing and replacing them all is brittle.
            // We just verify the bundle was created, then remove the string payloads to avoid timestamp failures.
            expect(resultObj.exports).toBeDefined();
            expect(resultObj.exports.markdown).toBeDefined();
            delete resultObj.exports;

            // We must also remove executionId from the nested report and json payload inside exports if they exist
            let resultStr = JSON.stringify(resultObj);
            
            // Normalize non-deterministic data
            resultStr = resultStr.replace(new RegExp(result.executionId, 'g'), 'STATIC-ID');
            // Remove collectionTime and collectedAt which vary by milliseconds
            resultStr = resultStr.replace(/"collectionTime":"[^"]+"/g, '"collectionTime":"STATIC-TIME"');
            resultStr = resultStr.replace(/"collectedAt":"[^"]+"/g, '"collectedAt":"STATIC-TIME"');
            // Remove generic timestamps globally
            resultStr = resultStr.replace(/"timestamp":"[^"]+"/g, '"timestamp":"STATIC-TIME"');
            // Remove random nodeIds generated by correlation engine
            resultStr = resultStr.replace(/"nodeId":"[^"]+"/g, '"nodeId":"STATIC-NODE"');
            
            if (i === 0) {
                baseline = resultStr;
            } else {
                expect(resultStr).toEqual(baseline);
            }
        }
    }, 60000); // 60s timeout for 100 runs
});
