import { useState, useCallback } from 'react';

const riskHex = (level) => ({ dangerous: '#ff2244', medium: '#ff8c00', low: '#ffdd00', safe: '#00ff88' }[level] || '#ff2244');
const hexToRgb = (hex) => {
  const h = hex.replace('#', '');
  return [
    parseInt(h.slice(0, 2), 16),
    parseInt(h.slice(2, 4), 16),
    parseInt(h.slice(4, 6), 16),
  ];
};

export default function usePdfExport() {
  const [exporting, setExporting] = useState(false);

  const exportPdf = useCallback(async (scan, user, aiAnalysis) => {
    if (!scan) return;

    setExporting(true);
    try {
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF({ unit: 'mm', format: 'a4' });
      const W = doc.internal.pageSize.getWidth();
      const H = doc.internal.pageSize.getHeight();
      const color = riskHex(scan.riskLevel);
      const [r, g, b] = hexToRgb(color);
      const vt = scan.breakdown?.virusTotal;
      const abuse = scan.breakdown?.abuseIPDB;
      const domainIntel = scan.breakdown?.domainIntel;
      const hashlookup = scan.breakdown?.hashlookup;

      // ── PAGE 1: COVER PAGE ──────────────────────────────────────────────────
      // Dark theme cover page for cyber aesthetic
      doc.setFillColor(10, 15, 30);
      doc.rect(0, 0, W, H, 'F');

      // Cyan accent top bar
      doc.setFillColor(0, 212, 255);
      doc.rect(0, 0, W, 4, 'F');

      // Title & Branding
      doc.setTextColor(0, 212, 255);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(26);
      doc.text('CYBERSHIELD X', 20, 60);

      doc.setFontSize(10);
      doc.setTextColor(148, 163, 184); // Muted slate
      doc.setFont('helvetica', 'normal');
      doc.text('A I - P O W E R E D   S E C U R I T Y   T R I A G E   A U D I T', 20, 70);

      // Decorative divider line
      doc.setDrawColor(34, 68, 102);
      doc.line(20, 80, W - 20, 80);

      // Main Assessment Title
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(18);
      doc.setFont('helvetica', 'bold');
      doc.text('ENTERPRISE VULNERABILITY ASSESSMENT', 20, 100);

      // Metadata widget
      const metaY = 120;
      doc.setFillColor(15, 23, 42); // slate-900
      doc.setDrawColor(30, 41, 59); // slate-800
      doc.roundedRect(20, metaY, W - 40, 90, 3, 3, 'FD');

      const drawCoverRow = (label, value, ry) => {
        doc.setTextColor(148, 163, 184);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(9);
        doc.text(label.toUpperCase(), 30, ry);
        doc.setTextColor(255, 255, 255);
        doc.setFont('helvetica', 'normal');
        doc.text(String(value ?? '—'), 90, ry);
      };

      drawCoverRow('Target Node', scan.target, metaY + 20);
      drawCoverRow('Target Type', (scan.targetType || 'IP').toUpperCase(), metaY + 35);
      drawCoverRow('Threat Score', `${scan.threatScore}/100 [ ${scan.riskLevel?.toUpperCase()} ]`, metaY + 50);
      drawCoverRow('Scan ID', scan._id || scan.id || 'N/A', metaY + 65);
      drawCoverRow('Assessment Date', new Date(scan.createdAt || Date.now()).toUTCString(), metaY + 80);

      // Bottom disclaimer / footer
      doc.setTextColor(71, 85, 105);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      doc.text('CONFIDENTIAL // LEVEL-4 RESTRICTED', W / 2, H - 25, { align: 'center' });
      doc.setFont('helvetica', 'normal');
      doc.text('Generated by CyberShield X Threat Intelligence Center', W / 2, H - 18, { align: 'center' });

      // ── PAGE 2: RISK METRICS & THREAT BREAKDOWN TABLES ──────────────────────────
      doc.addPage();
      
      // Page background
      doc.setFillColor(255, 255, 255);
      doc.rect(0, 0, W, H, 'F');

      // Top Header bar
      doc.setFillColor(15, 20, 30);
      doc.rect(0, 0, W, 20, 'F');
      doc.setTextColor(0, 212, 255);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.text('CYBERSHIELD X // RISK ASSESSMENT', 15, 13);

      doc.setTextColor(255, 255, 255);
      doc.setFontSize(8);
      doc.text(`TARGET: ${scan.target}`, W - 15, 13, { align: 'right' });

      let y = 35;

      // Risk score section
      doc.setTextColor(15, 23, 42);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.text('OVERALL SCORE DETAILS', 15, y);
      
      y += 6;
      doc.setFillColor(248, 250, 252);
      doc.setDrawColor(226, 232, 240);
      doc.roundedRect(15, y, W - 30, 28, 2, 2, 'FD');
      
      // Large Score display
      doc.setTextColor(r, g, b);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(22);
      doc.text(`${scan.threatScore}`, 25, y + 18);
      doc.setFontSize(10);
      doc.setTextColor(100, 110, 120);
      doc.text('/100', 40, y + 18);

      doc.setTextColor(15, 23, 42);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text(`SEVERITY LEVEL: ${scan.riskLevel?.toUpperCase()}`, 65, y + 12);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(71, 85, 105);
      doc.text('Threat score represents normalized risk indicators mapped from global intelligence feeds.', 65, y + 20);

      y += 40;

      // VirusTotal Breakdown
      doc.setTextColor(0, 120, 200);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.text('▶ VIRUSTOTAL TELEMETRY', 15, y);
      
      y += 4;
      doc.setFillColor(255, 255, 255);
      doc.setDrawColor(226, 232, 240);
      doc.roundedRect(15, y, W - 30, 36, 2, 2, 'FD');

      const row = (label, value, ry, indent = 22) => {
        doc.setTextColor(100, 116, 139);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8.5);
        doc.text(`• ${label.toUpperCase()}`, indent, ry);
        doc.setTextColor(15, 23, 42);
        doc.setFont('helvetica', 'normal');
        doc.text(String(value ?? '—'), W - 22, ry, { align: 'right' });
      };

      if (vt) {
        doc.setTextColor(vt.positives > 0 ? 200 : 0, vt.positives > 0 ? 30 : 150, 80);
        row('Detection Engines Flagged', `${vt.positives ?? 0} malicious engines / ${vt.total ?? 0} total`, y + 10);
        row('Last Global Scan Date', vt.scanDate ? new Date(vt.scanDate).toLocaleDateString() : '—', y + 18);
        row('Registrar Authority', vt.registrar || 'N/A', y + 26);
      } else {
        doc.setTextColor(100, 116, 139);
        doc.setFontSize(8.5);
        doc.setFont('helvetica', 'italic');
        doc.text('No VirusTotal threat signatures detected for this entity type.', 22, y + 18);
      }

      y += 48;

      // AbuseIPDB Breakdown
      doc.setTextColor(0, 120, 200);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.text('▶ ABUSEIPDB NETWORK INTELLIGENCE', 15, y);
      
      y += 4;
      doc.setFillColor(255, 255, 255);
      doc.roundedRect(15, y, W - 30, 36, 2, 2, 'FD');

      if (abuse) {
        row('Abuse Confidence Index', `${abuse.abuseConfidenceScore ?? 0}%`, y + 10);
        row('Registered Abuse Reports', String(abuse.totalReports ?? 0), y + 18);
        row('Origin Node Network (ISP)', abuse.isp || '—', y + 26);
      } else {
        doc.setTextColor(100, 116, 139);
        doc.setFontSize(8.5);
        doc.setFont('helvetica', 'italic');
        doc.text('No AbuseIPDB routing report data available for this target.', 22, y + 18);
      }

      y += 48;

      // Domain / Hash intelligence (if present)
      if ((domainIntel && !domainIntel.notApplicable) || (hashlookup && !hashlookup.notApplicable)) {
        doc.setTextColor(0, 120, 200);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(10);
        doc.text('▶ ASSOCIATED THREAT METADATA', 15, y);
        
        y += 4;
        doc.setFillColor(255, 255, 255);
        doc.roundedRect(15, y, W - 30, 26, 2, 2, 'FD');

        if (domainIntel && !domainIntel.notApplicable) {
          row('Domain Registered Age', domainIntel.ageDays ? `${domainIntel.ageDays} days` : 'N/A', y + 10);
          row('SPF / DMARC Security Records', `SPF: ${domainIntel.hasSpf ? 'YES' : 'NO'} | DMARC: ${domainIntel.hasDmarc ? 'YES' : 'NO'}`, y + 18);
        } else if (hashlookup && !hashlookup.notApplicable) {
          row('Known File Name', hashlookup.fileName || 'N/A', y + 10);
          row('Trusted Source Database', hashlookup.database || 'N/A', y + 18);
        }
      }

      // Footer
      doc.setFillColor(248, 250, 252);
      doc.rect(0, H - 15, W, 15, 'F');
      doc.setDrawColor(226, 232, 240);
      doc.line(15, H - 15, W - 15, H - 15);
      doc.setTextColor(148, 163, 184);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7.5);
      doc.text('Page 2 of 3 // CyberShield X Network Audit', W / 2, H - 6, { align: 'center' });

      // ── PAGE 3: AI RECOMMENDATIONS & HARDENING CHECKLIST ───────────────────────
      doc.addPage();

      doc.setFillColor(255, 255, 255);
      doc.rect(0, 0, W, H, 'F');

      // Top Header bar
      doc.setFillColor(15, 20, 30);
      doc.rect(0, 0, W, 20, 'F');
      doc.setTextColor(0, 212, 255);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.text('CYBERSHIELD X // AI SEC COPILOT REPORT', 15, 13);

      doc.setTextColor(255, 255, 255);
      doc.setFontSize(8);
      doc.text(`TARGET: ${scan.target}`, W - 15, 13, { align: 'right' });

      y = 35;

      doc.setTextColor(15, 23, 42);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.text('SENIOR CYBERSECURITY ANALYST TRIAGE', 15, y);

      y += 6;

      const ai = aiAnalysis || {
        executiveSummary: `The passive heuristics assessment calculated a threat score of ${scan.threatScore}/100. Running a dynamic multi-model AI analysis is recommended to generate custom remediation checklists.`,
        findings: [
          'Calculated network perimeter/IOC risk index is ' + (scan.riskLevel || 'SAFE').toUpperCase(),
          'Direct threat feed logs check complete.'
        ],
        recommendations: [
          'Establish continuous security monitoring of the target.',
          'Verify TLS cipher profiles and disable legacy key exchanges.',
          'Restrict incoming external access from suspicious IP scopes.'
        ],
        remediationPlan: 'Enable log collection, isolate high-risk asset endpoints, and schedule a deeper credentialed vulnerability scan.'
      };

      // Executive Summary Block
      doc.setFillColor(248, 250, 252);
      doc.setDrawColor(226, 232, 240);
      doc.roundedRect(15, y, W - 30, 45, 2, 2, 'FD');

      doc.setTextColor(0, 120, 200);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9.5);
      doc.text('EXECUTIVE SUMMARY', 20, y + 8);

      doc.setTextColor(51, 65, 85);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      const splitSummary = doc.splitTextToSize(ai.executiveSummary || 'No summary provided.', W - 40);
      doc.text(splitSummary, 20, y + 16);

      y += 55;

      // Findings & Recommendations
      doc.setTextColor(15, 23, 42);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10.5);
      doc.text('IDENTIFIED THREAT FINDINGS', 15, y);
      y += 4;

      if (ai.findings && ai.findings.length > 0) {
        ai.findings.slice(0, 4).forEach((finding) => {
          doc.setTextColor(220, 38, 38);
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(8.5);
          doc.text('[CRITICAL]', 15, y + 4);
          doc.setTextColor(51, 65, 85);
          doc.setFont('helvetica', 'normal');
          const splitFinding = doc.splitTextToSize(finding, W - 45);
          doc.text(splitFinding, 35, y + 4);
          y += (splitFinding.length * 4.5) + 2;
        });
      } else {
        doc.setTextColor(71, 85, 105);
        doc.setFont('helvetica', 'italic');
        doc.text('No critical threat findings reported.', 15, y + 4);
        y += 10;
      }

      y += 6;

      doc.setTextColor(15, 23, 42);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10.5);
      doc.text('RECOMMENDED POLICY & HARDENING', 15, y);
      y += 4;

      if (ai.recommendations && ai.recommendations.length > 0) {
        ai.recommendations.slice(0, 4).forEach((rec) => {
          doc.setTextColor(22, 163, 74);
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(8.5);
          doc.text('[ACTION]', 15, y + 4);
          doc.setTextColor(51, 65, 85);
          doc.setFont('helvetica', 'normal');
          const splitRec = doc.splitTextToSize(rec, W - 45);
          doc.text(splitRec, 35, y + 4);
          y += (splitRec.length * 4.5) + 2;
        });
      } else {
        doc.setTextColor(71, 85, 105);
        doc.setFont('helvetica', 'italic');
        doc.text('No policy recommendations provided.', 15, y + 4);
        y += 10;
      }

      y += 6;

      // Remediation Plan Block
      doc.setTextColor(15, 23, 42);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10.5);
      doc.text('DETAILED REMEDIATION PLAN', 15, y);
      y += 4;

      doc.setTextColor(51, 65, 85);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      const splitPlan = doc.splitTextToSize(ai.remediationPlan || 'No plan provided.', W - 30);
      doc.text(splitPlan, 15, y + 4);

      // Footer
      doc.setFillColor(248, 250, 252);
      doc.rect(0, H - 15, W, 15, 'F');
      doc.setDrawColor(226, 232, 240);
      doc.line(15, H - 15, W - 15, H - 15);
      doc.setTextColor(148, 163, 184);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7.5);
      doc.text('Page 3 of 3 // CyberShield X Senior Analyst Report', W / 2, H - 6, { align: 'center' });

      doc.save(`NEXUS-REPORT-${scan._id || scan.id || Date.now()}.pdf`);
    } catch (err) {
      console.error('[usePdfExport]', err);
      // eslint-disable-next-line no-alert
      alert('PDF failed. Run: cd client && npm install jspdf');
    } finally {
      setExporting(false);
    }
  }, []);

  const exportAdminProfilePdf = useCallback(async (reportData, adminUser) => {
    if (!reportData || !reportData.user) return;
    setExporting(true);
    try {
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF({ unit: 'mm', format: 'a4' });
      const W = doc.internal.pageSize.getWidth();
      const H = doc.internal.pageSize.getHeight();
      
      // Background Base
      doc.setFillColor(255, 255, 255);
      doc.rect(0, 0, W, H, 'F');

      // Watermark
      doc.setTextColor(240, 240, 245);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(70);
      doc.text('CYBERSHIELD', W / 2, H / 2, { align: 'center', angle: -45 });

      // Header Block
      doc.setFillColor(15, 20, 30);
      doc.rect(0, 0, W, 35, 'F');
      
      doc.setTextColor(0, 212, 255);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(22);
      doc.text('CYBERSHIELD X', 14, 18);
      
      doc.setFontSize(8);
      doc.setTextColor(150, 180, 210);
      doc.setFont('helvetica', 'normal');
      doc.text('A D M I N   U S E R   P R O F I L E', 15, 26);
      
      doc.setTextColor(200, 210, 220);
      doc.setFontSize(7);
      doc.text(`DATE GENERATED  :  ${new Date().toLocaleString()}`, W - 14, 18, { align: 'right' });
      doc.text(`ADMIN OFFICER  :  ${adminUser?.username?.toUpperCase() || 'SYSTEM'}`, W - 14, 24, { align: 'right' });
      doc.text(`DOC CLASSIFICATION:  SENSITIVE DATA`, W - 14, 30, { align: 'right' });

      let y = 50;
      doc.setTextColor(40, 50, 60);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(16);
      doc.text('TARGET INTELLIGENCE PROFILE', 14, y);

      y += 10;
      doc.setFillColor(245, 248, 252);
      doc.setDrawColor(200, 210, 220);
      doc.roundedRect(14, y, W - 28, 48, 2, 2, 'FD');

      const row = (label, value, ry) => {
        doc.setTextColor(80, 100, 120);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(9);
        doc.text(`• ${label.toUpperCase()}`, 20, ry);
        doc.setTextColor(0, 0, 0);
        doc.setFont('helvetica', 'normal');
        doc.text(String(value ?? '—'), W - 20, ry, { align: 'right' });
      };

      row('Username', reportData.user.username, y + 10);
      row('Email Address', reportData.user.email, y + 20);
      row('Verification Status', reportData.user.emailVerified ? 'VERIFIED' : 'UNVERIFIED', y + 30);
      row('2FA Status', reportData.user.twoFactorEnabled ? 'ENABLED' : 'DISABLED', y + 40);

      y += 60;
      doc.setTextColor(40, 50, 60);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.text('OPERATIONAL METRICS', 14, y);

      y += 10;
      doc.setFillColor(255, 255, 255);
      doc.roundedRect(14, y, W - 28, 30, 2, 2, 'FD');

      const totalScans = reportData.scans?.length || 0;
      const breachChecks = reportData.activities?.filter(a => a.action?.startsWith('BREACH_CHECK'))?.length || 0;

      row('Total Security Scans', String(totalScans), y + 10);
      row('Data Breach Checks', String(breachChecks), y + 20);

      // Footer
      doc.setFillColor(245, 246, 248);
      doc.rect(0, H - 20, W, 20, 'F');
      
      doc.setDrawColor(200, 200, 210);
      doc.line(14, H - 20, W - 14, H - 20);
      
      doc.setTextColor(120, 130, 140);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.text('Provided by CyberShield X', W / 2, H - 8, { align: 'center' });

      doc.save(`USER-PROFILE-${reportData.user._id}.pdf`);
    } catch (err) {
      console.error('[exportAdminProfilePdf]', err);
    } finally {
      setExporting(false);
    }
  }, []);

  const exportBreachPdf = useCallback(async (result, target, user) => {
    if (!result) return;
    setExporting(true);
    try {
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF({ unit: 'mm', format: 'a4' });
      const W = doc.internal.pageSize.getWidth();
      const H = doc.internal.pageSize.getHeight();
      
      const isBreached = result.found;
      const color = isBreached ? '#ff2244' : '#00ff88';
      const [r, g, b] = hexToRgb(color);

      // Background Base
      doc.setFillColor(255, 255, 255);
      doc.rect(0, 0, W, H, 'F');

      // Header Block
      doc.setFillColor(15, 20, 30);
      doc.rect(0, 0, W, 35, 'F');
      
      doc.setTextColor(0, 212, 255);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(22);
      doc.text('CYBERSHIELD X', 14, 18);
      
      doc.setFontSize(8);
      doc.setTextColor(150, 180, 210);
      doc.setFont('helvetica', 'normal');
      doc.text('D A R K   W E B   I N T E L L I G E N C E   R E P O R T', 15, 26);
      
      doc.setTextColor(200, 210, 220);
      doc.setFontSize(7);
      doc.text(`DATE GENERATED  :  ${new Date().toLocaleString()}`, W - 14, 18, { align: 'right' });
      doc.text(`AUTHORIZED SIG  :  ${user?.username?.toUpperCase() || 'SYSTEM'}`, W - 14, 24, { align: 'right' });
      
      doc.setFillColor(r, g, b);
      doc.rect(0, 35, W, 2, 'F');

      let y = 50;
      doc.setTextColor(r, g, b);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(18);
      doc.text(isBreached ? 'CRITICAL COMPROMISE DETECTED' : 'PERIMETER SECURE', 14, y);

      y += 10;
      doc.setFillColor(245, 248, 252);
      doc.setDrawColor(200, 210, 220);
      doc.roundedRect(14, y, W - 28, 30, 2, 2, 'FD');

      const row = (label, value, ry) => {
        doc.setTextColor(80, 100, 120);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(9);
        doc.text(`• ${label.toUpperCase()}`, 20, ry);
        doc.setTextColor(0, 0, 0);
        doc.setFont('helvetica', 'normal');
        doc.text(String(value ?? '—'), W - 20, ry, { align: 'right' });
      };

      row('Analyzed Target', target, y + 10);
      row('Methodology', result.methodology || 'Dark Web Correlation', y + 20);

      y += 40;

      if (isBreached && result.leaks) {
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(12);
        doc.text(`CONFIRMED LEAKS: ${result.leaks.length}`, 14, y);
        y += 10;

        result.leaks.forEach((leak, idx) => {
          if (y > 250) { doc.addPage(); y = 20; }
          doc.setFillColor(255, 240, 240);
          doc.setDrawColor(255, 100, 100);
          doc.roundedRect(14, y, W - 28, 45, 2, 2, 'FD');
          
          doc.setTextColor(200, 0, 0);
          doc.setFontSize(11);
          doc.setFont('helvetica', 'bold');
          doc.text(leak.name, 18, y + 8);
          
          doc.setTextColor(100, 100, 100);
          doc.setFontSize(8);
          doc.setFont('helvetica', 'normal');
          doc.text(`Date: ${leak.date} | Hacker Group: ${leak.hackerGroup}`, 18, y + 14);
          
          doc.setTextColor(0, 0, 0);
          const desc = doc.splitTextToSize(leak.description || '', W - 36);
          doc.text(desc, 18, y + 22);
          
          const classes = leak.dataClasses?.join(', ') || '';
          doc.setTextColor(200, 50, 50);
          doc.setFont('helvetica', 'bold');
          doc.text(`Data Compromised: ${classes}`, 18, y + 38);

          y += 50;
        });
      }

      // Footer
      doc.setFillColor(245, 246, 248);
      doc.rect(0, H - 20, W, 20, 'F');
      
      doc.setTextColor(120, 130, 140);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.text('Provided by CyberShield X', W / 2, H - 8, { align: 'center' });

      doc.save(`DARK-WEB-REPORT-${target}.pdf`);
    } catch (err) {
      console.error('[exportBreachPdf]', err);
    } finally {
      setExporting(false);
    }
  }, []);

  const exportToolReportPdf = useCallback(async (toolName, target, result, user) => {
    if (!result) return;
    setExporting(true);
    try {
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF({ unit: 'mm', format: 'a4' });
      const W = doc.internal.pageSize.getWidth();
      const H = doc.internal.pageSize.getHeight();
      
      const riskColor = result.riskLevel ? riskHex(result.riskLevel) : '#00bfff';
      const [r, g, b] = hexToRgb(riskColor);

      // Background Base
      doc.setFillColor(255, 255, 255);
      doc.rect(0, 0, W, H, 'F');

      // Header Block
      doc.setFillColor(15, 20, 30);
      doc.rect(0, 0, W, 35, 'F');
      
      doc.setTextColor(0, 212, 255);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(22);
      doc.text('CYBERSHIELD X', 14, 18);
      
      doc.setFontSize(8);
      doc.setTextColor(150, 180, 210);
      doc.setFont('helvetica', 'normal');
      doc.text(`T O O L   I N T E L L I G E N C E :   ${toolName.toUpperCase()}`, 15, 26);
      
      doc.setTextColor(200, 210, 220);
      doc.setFontSize(7);
      doc.text(`DATE GENERATED  :  ${new Date().toLocaleString()}`, W - 14, 18, { align: 'right' });
      doc.text(`AUTHORIZED SIG  :  ${user?.username?.toUpperCase() || 'SYSTEM'}`, W - 14, 24, { align: 'right' });
      
      doc.setFillColor(r, g, b);
      doc.rect(0, 35, W, 2, 'F');

      let y = 50;
      doc.setTextColor(40, 50, 60);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(18);
      doc.text(`${toolName.toUpperCase()} ANALYSIS REPORT`, 14, y);

      y += 10;
      doc.setFillColor(245, 248, 252);
      doc.setDrawColor(200, 210, 220);
      doc.roundedRect(14, y, W - 28, 45, 2, 2, 'FD');

      const row = (label, value, ry) => {
        doc.setTextColor(80, 100, 120);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(9);
        doc.text(`• ${label.toUpperCase()}`, 20, ry);
        doc.setTextColor(0, 0, 0);
        doc.setFont('helvetica', 'normal');
        doc.text(String(value ?? '—').substring(0, 70), W - 20, ry, { align: 'right' });
      };

      row('Analyzed Target', target || 'File/Text Input', y + 10);
      if (result.riskLevel) row('Assessed Risk Level', result.riskLevel.toUpperCase(), y + 20);
      if (result.score !== undefined) row('Threat Score', String(result.score), y + 30);
      if (result.verifyingAuthority) row('Verifying Authority', result.verifyingAuthority, y + 40);

      y += 60;
      doc.setTextColor(0, 120, 200);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.text('▶ ANALYSIS RESULTS & METADATA', 14, y);
      
      y += 5;
      doc.setTextColor(40, 50, 60);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      
      // Auto-print generic keys
      const skipKeys = ['riskLevel', 'score', 'verifyingAuthority', 'rawAnalysis'];
      Object.entries(result).forEach(([k, v]) => {
        if (skipKeys.includes(k) || typeof v === 'object') return;
        if (y > H - 40) { doc.addPage(); y = 20; }
        y += 8;
        doc.setFont('helvetica', 'bold');
        doc.text(`${k.toUpperCase()}:`, 14, y);
        doc.setFont('helvetica', 'normal');
        doc.text(String(v), 60, y, { maxWidth: W - 74 });
      });

      if (result.rawAnalysis) {
        if (y > H - 55) { doc.addPage(); y = 20; }
        y += 12;
        doc.setTextColor(0, 120, 200);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(10);
        doc.text('▶ TERMINAL EXECUTION LOGS', 14, y);
        
        y += 8;
        doc.setFont('courier', 'normal');
        doc.setFontSize(7.5);
        doc.setTextColor(50, 50, 50);
        
        const lines = String(result.rawAnalysis).split('\n');
        for (const line of lines) {
          const cleanLine = line.replace(/\r/g, '');
          const splitLines = doc.splitTextToSize(cleanLine, W - 28);
          for (const sLine of splitLines) {
            if (y > H - 25) {
              doc.addPage();
              y = 20;
              // Reset font state on new page
              doc.setFont('courier', 'normal');
              doc.setFontSize(7.5);
              doc.setTextColor(50, 50, 50);
            }
            doc.text(sLine, 14, y);
            y += 4;
          }
        }
      }

      // Footer
      doc.setFillColor(245, 246, 248);
      doc.rect(0, H - 20, W, 20, 'F');
      
      doc.setTextColor(120, 130, 140);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.text('Provided by CyberShield X', W / 2, H - 8, { align: 'center' });

      doc.save(`${toolName.replace(/\s+/g, '-').toUpperCase()}-REPORT.pdf`);
    } catch (err) {
      console.error('[exportToolReportPdf]', err);
    } finally {
      setExporting(false);
    }
  }, []);

  return { exportPdf, exportAdminProfilePdf, exportBreachPdf, exportToolReportPdf, exporting };
}
