/**
 * @module AuthorizationContext
 * @description Contextual object generated by AuthorizationService to pass into PermissionManager.
 */
class AuthorizationContext {
    constructor({ userId, roles = [], permissions = [], resource, action, environment = {} }) {
        this.userId = userId;
        this.roles = Object.freeze([...roles]);
        this.permissions = Object.freeze([...permissions]);
        this.resource = resource;
        this.action = action;
        this.environment = Object.freeze({ ...environment });
        
        // Ensure backward compatibility with existing PermissionManager heuristic (e.g., checks role string)
        this.role = roles.includes('admin') ? 'admin' : (roles[0] || 'guest');
        
        Object.freeze(this);
    }
}
module.exports = AuthorizationContext;
