import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Link } from 'react-router-dom';

const sections = [
  {
    id: 'acceptance',
    title: '1. Acceptance of Terms',
    icon: '📋',
    content: [
      'By creating an account or accessing CyberShield X ("the Platform"), you confirm that you have read, understood, and agree to be legally bound by these Terms of Service ("Terms").',
      'If you are using CyberShield X on behalf of an organization, you represent that you have authority to bind that organization to these Terms.',
      'You must be at least 16 years of age to use this platform. By using our services, you confirm this eligibility.',
      'We reserve the right to update these Terms. Continued use after changes constitutes acceptance.',
    ],
  },
  {
    id: 'permitted-use',
    title: '2. Permitted Use',
    icon: '✅',
    items: [
      { label: 'Defensive Security', value: 'Analyzing URLs, IPs, domains, and file hashes for threats affecting YOU or your organization' },
      { label: 'Research', value: 'Security research on systems you own or have explicit written permission to test' },
      { label: 'Education', value: 'Learning about cybersecurity threats in an educational context' },
      { label: 'Incident Response', value: 'Investigating security incidents within your own infrastructure' },
    ],
  },
  {
    id: 'prohibited',
    title: '3. Prohibited Activities',
    icon: '🚫',
    content: [
      '**Unauthorized scanning**: You may NOT scan systems, networks, or assets you do not own or lack explicit written authorization to test.',
      '**Malicious use**: You may NOT use our platform to facilitate attacks, launch exploits, or cause harm to third parties.',
      '**Automated scraping**: You may NOT programmatically scrape, bulk-query, or abuse our API without prior written agreement.',
      '**Circumventing limits**: You may NOT create multiple accounts to bypass rate limits or usage quotas.',
      '**False reporting**: You may NOT submit fake or fabricated threat reports to manipulate community intelligence.',
      '**Re-selling data**: You may NOT resell, redistribute, or commercially exploit scan results without a commercial license.',
    ],
    note: 'Violation of these rules will result in immediate account termination and may be reported to law enforcement authorities.',
  },
  {
    id: 'account',
    title: '4. Account & Security Responsibilities',
    icon: '🔐',
    content: [
      'You are responsible for maintaining the confidentiality of your password and all activity under your account.',
      'You must immediately notify us at security@cybershieldx.com if you suspect unauthorized access to your account.',
      'CyberShield X uses industry-standard security (bcrypt passwords, JWT tokens, 2FA) but cannot guarantee absolute security.',
      'You agree to use strong passwords and enable Two-Factor Authentication for maximum account security.',
    ],
  },
  {
    id: 'api-usage',
    title: '5. API & Third-Party Services',
    icon: '🔌',
    content: [
      'When you submit a target (URL, IP, domain, hash) for scanning, that data may be sent to third-party threat intelligence APIs including VirusTotal, AbuseIPDB, and CIRCL Hashlookup.',
      'By using our scanning features, you consent to this data sharing for the purpose of threat analysis.',
      'Our AI analysis features use Google Gemini AI. Security queries may be processed by Google\'s infrastructure.',
      'We are not responsible for the accuracy or availability of third-party threat intelligence data.',
    ],
  },
  {
    id: 'intellectual-property',
    title: '6. Intellectual Property',
    icon: '©️',
    content: [
      'All platform source code, UI designs, algorithms, and documentation are the intellectual property of CyberShield X Technologies.',
      'Scan results generated by our platform are provided for your personal/organizational use. You may not redistribute them commercially.',
      'Community-contributed threat notes remain the intellectual property of their authors but grant CyberShield X a license to display and use them within the platform.',
    ],
  },
  {
    id: 'disclaimer',
    title: '7. Disclaimer of Warranties',
    icon: '⚠️',
    content: [
      'CyberShield X is provided "AS IS" and "AS AVAILABLE" without any warranties of any kind, express or implied.',
      'We do not warrant that the platform will be uninterrupted, error-free, or that all threats will be detected.',
      'Cybersecurity threat intelligence is probabilistic, not absolute. False positives and false negatives can and do occur.',
      '**IMPORTANT**: Our results should supplement — not replace — professional cybersecurity assessment and human judgment.',
    ],
    note: 'For production-critical or high-stakes security decisions, we strongly recommend engaging a certified cybersecurity professional.',
  },
  {
    id: 'liability',
    title: '8. Limitation of Liability',
    icon: '⚖️',
    content: [
      'To the maximum extent permitted by applicable law, CyberShield X Technologies shall not be liable for any indirect, incidental, special, consequential, or punitive damages.',
      'Our total liability to you for any claims arising from these Terms or your use of the platform shall not exceed the amount you paid for our services in the past 12 months.',
      'These limitations apply regardless of the theory of liability (contract, tort, negligence, strict liability) and even if we have been advised of the possibility of such damages.',
    ],
  },
  {
    id: 'termination',
    title: '9. Account Termination',
    icon: '🔚',
    content: [
      'You may delete your account at any time via the Settings page. All data will be permanently purged as described in our Privacy Policy.',
      'We reserve the right to suspend or terminate accounts that violate these Terms, engage in abusive behavior, or pose a security risk to our platform.',
      'Upon termination for cause, we may retain minimal data (IP logs) for legal compliance and fraud prevention purposes for up to 6 months.',
    ],
  },
  {
    id: 'governing-law',
    title: '10. Governing Law & Disputes',
    icon: '🏛️',
    content: [
      'These Terms are governed by the laws of India and shall be subject to the jurisdiction of courts in India.',
      'Any disputes arising under these Terms shall first be attempted through good-faith negotiation. If unresolved, disputes shall be settled through binding arbitration in accordance with Indian Arbitration laws.',
      'For concerns or legal notices, contact us at: legal@cybershieldx.com',
    ],
  },
];

export default function TermsOfServicePage() {
  const [expandedSection, setExpandedSection] = useState(null);

  return (
    <div className="max-w-4xl mx-auto py-12 px-4">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="mb-12"
      >
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-cyber-accent/10 border border-cyber-accent/20 mb-4">
          <span className="w-2 h-2 rounded-full bg-cyber-accent animate-pulse" />
          <span className="font-mono text-[10px] text-cyber-accent uppercase tracking-widest">Legal Document</span>
        </div>
        <h1 className="text-4xl font-display font-black text-white tracking-tight mb-3">Terms of Service</h1>
        <p className="text-cyber-muted font-mono text-xs uppercase tracking-[.3em]">
          Effective: April 2026 · Version 2.0 · Binding Agreement
        </p>
        <p className="mt-4 text-sm text-cyber-text/70 leading-relaxed">
          Please read these Terms of Service carefully before using CyberShield X. By using our platform, you agree to these terms.
          If you disagree with any part, discontinue use immediately.
        </p>
        <div className="mt-4 flex gap-3 flex-wrap">
          <Link to="/privacy" className="text-xs font-mono text-cyber-accent hover:underline">
            → Privacy Policy
          </Link>
          <span className="text-cyber-muted text-xs">|</span>
          <a href="mailto:legal@cybershieldx.com" className="text-xs font-mono text-cyber-muted hover:text-cyber-accent">
            → legal@cybershieldx.com
          </a>
        </div>
      </motion.div>

      <div className="space-y-4">
        {sections.map((section, index) => (
          <motion.div
            key={section.id}
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: index * 0.04 }}
            className="cyber-bento-card border-white/5 hover:border-cyber-accent/20 transition-all overflow-hidden"
          >
            <button
              onClick={() => setExpandedSection(expandedSection === section.id ? null : section.id)}
              className="w-full flex items-center justify-between p-6 text-left"
            >
              <div className="flex items-center gap-3">
                <span className="text-xl">{section.icon}</span>
                <h2 className="text-sm font-display font-bold text-white uppercase tracking-widest">{section.title}</h2>
              </div>
              <motion.span
                animate={{ rotate: expandedSection === section.id ? 180 : 0 }}
                className="text-cyber-accent text-lg"
              >
                ▾
              </motion.span>
            </button>

            <AnimatePresence>
              {expandedSection === section.id && (
                <motion.div
                  initial={{ height: 0, opacity: 0 }}
                  animate={{ height: 'auto', opacity: 1 }}
                  exit={{ height: 0, opacity: 0 }}
                  className="px-6 pb-6"
                >
                  <div className="border-t border-white/5 pt-4 space-y-3">
                    {section.content && section.content.map((line, i) => (
                      <p key={i} className="text-sm text-cyber-text/80 leading-relaxed">
                        {line.startsWith('**') ? (
                          <>
                            <span className="font-bold text-cyber-accent">{line.match(/\*\*(.*?)\*\*/)?.[1]}:</span>{' '}
                            {line.replace(/\*\*(.*?)\*\*:?\s*/g, '')}
                          </>
                        ) : line}
                      </p>
                    ))}

                    {section.items && (
                      <div className="space-y-2 mt-2">
                        {section.items.map((item, ii) => (
                          <div key={ii} className="flex gap-3 items-start py-2 border-b border-white/5 last:border-0">
                            <span className="font-mono text-[11px] text-cyber-accent min-w-[160px] shrink-0">{item.label}</span>
                            <span className="text-sm text-cyber-text/70">{item.value}</span>
                          </div>
                        ))}
                      </div>
                    )}

                    {section.note && (
                      <div className="mt-3 p-3 rounded-lg bg-yellow-500/5 border border-yellow-500/20">
                        <p className="text-xs text-yellow-400/90 leading-relaxed">⚠️ {section.note}</p>
                      </div>
                    )}
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </motion.div>
        ))}
      </div>

      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.8 }}
        className="mt-10 p-6 rounded-2xl bg-white/5 border border-white/10 text-center"
      >
        <p className="text-[10px] font-mono text-cyber-muted uppercase tracking-widest">
          Last Updated: April 2026 · CyberShield X v2.0 · Governed under Indian IT Act 2000
        </p>
        <p className="text-[10px] font-mono text-cyber-muted mt-1">
          Legal questions? Contact us at <span className="text-cyber-accent">legal@cybershieldx.com</span>
        </p>
      </motion.div>
    </div>
  );
}
