/**
 * UtilityToolView Inline Styles
 * Extracted styles to keep component JSX clean and readable in Cyprus/Sand theme.
 */
export const styles = {
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(12, 1fr)',
    gap: '24px',
  },
  mainColumn: {
    gridColumn: 'span 8',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  sideColumn: {
    gridColumn: 'span 4',
  },
  innerContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    textAlign: 'left',
  },
  card: {
    background: 'var(--cyber-card)',
    border: '1px solid rgba(0, 71, 65, 0.1)',
    borderRadius: '12px',
    padding: '24px',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    textAlign: 'left',
  },
  cardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottom: '1px solid rgba(0, 71, 65, 0.08)',
    paddingBottom: '16px',
  },
  cardTitle: {
    margin: 0,
    fontFamily: "'Inter', sans-serif",
    fontSize: '15px',
    fontWeight: 700,
    color: 'var(--cyber-text)',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  textarea: {
    width: '100%',
    background: 'rgba(0, 71, 65, 0.04)',
    border: '1px solid rgba(0, 71, 65, 0.15)',
    borderRadius: '10px',
    padding: '16px',
    fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
    fontSize: '13px',
    color: 'var(--cyber-text)',
    outline: 'none',
    height: '96px',
    resize: 'none',
    boxSizing: 'border-box',
    transition: 'border-color 0.2s',
  },
  textareaReadOnly: {
    width: '100%',
    background: 'rgba(0, 71, 65, 0.02)',
    border: '1px solid rgba(0, 71, 65, 0.08)',
    borderRadius: '10px',
    padding: '16px',
    fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
    fontSize: '13px',
    color: 'var(--cyber-accent)',
    outline: 'none',
    height: '96px',
    resize: 'none',
    boxSizing: 'border-box',
  },
  textInput: {
    width: '100%',
    background: 'rgba(0, 71, 65, 0.04)',
    border: '1px solid rgba(0, 71, 65, 0.15)',
    borderRadius: '10px',
    padding: '14px 16px',
    fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
    fontSize: '13px',
    color: 'var(--cyber-text)',
    outline: 'none',
    boxSizing: 'border-box',
  },
  twoColGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
    gap: '16px',
  },
  threeColGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '12px',
  },
  sectionHeader: {
    margin: 0,
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: '11px',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.1em',
  },
  pre: {
    margin: 0,
    background: 'rgba(0, 71, 65, 0.05)',
    padding: '12px',
    borderRadius: '10px',
    fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
    fontSize: '11px',
    overflowX: 'auto',
  },
  codeBlock: {
    display: 'block',
    background: 'rgba(186,45,63,0.05)',
    padding: '12px',
    borderRadius: '8px',
    fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
    fontSize: '11px',
    color: 'var(--cyber-red)',
    wordBreak: 'break-all',
  },
  errorBox: {
    padding: '16px',
    borderRadius: '10px',
    background: 'rgba(186,45,63,0.05)',
    border: '1px solid rgba(186,45,63,0.25)',
    color: 'var(--cyber-red)',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: '12px',
  },
  btnGroup: {
    display: 'flex',
    border: '1px solid rgba(0, 71, 65, 0.15)',
    borderRadius: '8px',
    overflow: 'hidden',
    background: 'rgba(0, 71, 65, 0.03)',
  },
  btnGroupBtn: {
    border: 'none',
    padding: '6px 12px',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: '10px',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  inputStack: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  stackLabel: {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: '10px',
    color: 'var(--cyber-muted)',
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
  },
  diagnosticPill: {
    background: 'rgba(0, 71, 65, 0.03)',
    border: '1px solid rgba(0, 71, 65, 0.08)',
    borderRadius: '10px',
    padding: '12px 14px',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  diagnosticLabel: {
    margin: 0,
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: '9px',
    color: 'var(--cyber-muted)',
    textTransform: 'uppercase',
  },
  diagnosticValue: {
    margin: 0,
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: '12px',
    fontWeight: 700,
    color: 'var(--cyber-accent)',
    wordBreak: 'break-all',
  },
  tableWrapper: {
    border: '1px solid rgba(0, 71, 65, 0.1)',
    borderRadius: '12px',
    overflow: 'hidden',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: '12px',
  },
  thRow: {
    background: 'rgba(0, 71, 65, 0.04)',
    textAlign: 'left',
  },
  th: {
    padding: '12px 16px',
    color: 'var(--cyber-muted)',
    fontWeight: 600,
  },
  tr: {
    borderBottom: '1px solid rgba(0, 71, 65, 0.06)',
  },
  tdKey: {
    padding: '12px 16px',
    color: 'var(--cyber-text)',
    fontWeight: 700,
  },
  tdValue: {
    padding: '12px 16px',
    color: 'var(--cyber-accent)',
    wordBreak: 'break-all',
  },
  tdPlaceholder: {
    padding: '24px 16px',
    color: 'var(--cyber-muted)',
    textAlign: 'center',
    fontStyle: 'italic',
  },

  /* Sidekick */
  sidekickCard: {
    background: 'var(--cyber-card)',
    border: '1px solid rgba(0, 71, 65, 0.1)',
    borderRadius: '12px',
    padding: '20px',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    height: '450px',
    textAlign: 'left',
  },
  sidekickTitle: {
    margin: '0 0 16px 0',
    fontFamily: "'Inter', sans-serif",
    fontSize: '13px',
    fontWeight: 700,
    color: 'var(--cyber-text)',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  sidekickIndicator: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    background: 'var(--cyber-accent)',
  },
  sidekickHistory: {
    flex: 1,
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    marginBottom: '16px',
    paddingRight: '4px',
  },
  msgBubble: {
    padding: '12px',
    borderRadius: '10px',
    border: '1px solid',
    boxSizing: 'border-box',
  },
  msgRole: {
    margin: '0 0 4px 0',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: '9px',
    fontWeight: 700,
    letterSpacing: '0.08em',
  },
  msgText: {
    fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
    fontSize: '12px',
    lineHeight: 1.6,
  },
  sidekickForm: {
    display: 'flex',
    gap: '8px',
  },
  sidekickInput: {
    flex: 1,
    background: 'rgba(0, 71, 65, 0.04)',
    border: '1px solid rgba(0, 71, 65, 0.15)',
    borderRadius: '10px',
    padding: '10px 14px',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: '12px',
    color: 'var(--cyber-text)',
    outline: 'none',
  },
  sidekickSendBtn: {
    background: 'rgba(0, 71, 65, 0.05)',
    border: '1px solid rgba(0, 71, 65, 0.25)',
    color: 'var(--cyber-accent)',
    borderRadius: '10px',
    padding: '10px 16px',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: '11px',
    fontWeight: 700,
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
};

export default styles;
