const UserDTO = require('./dto/UserDTO');
const IRepository = require('../../shared/IRepository');

/**
 * @module UserRepository
 * @description Storage abstraction wrapper for Users.
 */
class UserRepository extends IRepository {
    /**
     * @param {Object} deps
     * @param {import('../chatbot_core/storage/IStorageProvider')} deps.storageProvider
     */
    constructor(deps) {
        super();
        if (!deps || !deps.storageProvider) {
            throw new Error('UserRepository requires storageProvider');
        }
        this.storageProvider = deps.storageProvider;
        this.collectionName = 'users';
    }

    /**
     * @param {string} id 
     * @returns {Promise<UserDTO|null>}
     */
    async findById(id) {
        const doc = await this.storageProvider.findById(this.collectionName, id);
        if (!doc) return null;
        return new UserDTO(doc);
    }

    /**
     * @param {Object} query 
     * @returns {Promise<UserDTO|null>}
     */
    async findOne(query) {
        const doc = await this.storageProvider.findOne(this.collectionName, query);
        if (!doc) return null;
        return new UserDTO(doc);
    }

    /**
     * @param {Object} query 
     * @returns {Promise<Array<UserDTO>>}
     */
    async findMany(query = {}) {
        const docs = await this.storageProvider.findMany(this.collectionName, query);
        return docs.map(doc => new UserDTO(doc));
    }

    /**
     * @param {Object} entityDTO 
     * @returns {Promise<UserDTO>}
     */
    async create(entityDTO) {
        // ID might be auto-generated by the underlying provider if not provided
        const doc = await this.storageProvider.save(this.collectionName, entityDTO.id, entityDTO);
        return new UserDTO(doc);
    }

    /**
     * @param {Object} entityDTO 
     * @returns {Promise<UserDTO>}
     */
    async update(entityDTO) {
        const updates = { ...entityDTO };
        delete updates.id;
        delete updates.createdAt;
        
        const doc = await this.storageProvider.update(this.collectionName, entityDTO.id, updates);
        return new UserDTO(doc);
    }

    /**
     * @param {string} id 
     * @returns {Promise<boolean>}
     */
    async delete(id) {
        return await this.storageProvider.delete(this.collectionName, id);
    }

    /**
     * @param {Object} query 
     * @returns {Promise<boolean>}
     */
    async exists(query) {
        return await this.storageProvider.exists(this.collectionName, query);
    }

    /**
     * @param {Object} query 
     * @returns {Promise<number>}
     */
    async count(query) {
        return await this.storageProvider.count(this.collectionName, query);
    }

    /**
     * @param {Object} query 
     * @param {number} page 
     * @param {number} limit 
     * @returns {Promise<{data: Array<UserDTO>, total: number, page: number, limit: number}>}
     */
    async paginate(query, page = 1, limit = 10) {
        const result = await this.storageProvider.paginate(this.collectionName, query, page, limit);
        return {
            ...result,
            data: result.data.map(doc => new UserDTO(doc))
        };
    }
}

module.exports = UserRepository;
